### ISSUE TITLE
Feature Request: Remember currently playing song, playlist after closing and reopening the app.

### ISSUE THREAD

**Issue by LovedByTheLord** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1115]
Hi,

It would be really cool if the app would remember the song that is playing, its current location, and the current playlist when the app is closed an reopened.  I typically just shuffle all the songs in my library and this would save a few clicks to get the music playing again the next time I open the app.  This behavior can be seen in Spotify.

Thanks for the consideration!

**Comment by MarshallOfSound** [comment]
@LovedByTheLord The current "location" in GPM is remembered but we can't start the same song playing again when you reopen the app.  This is because the songs are assigned random ID's and aren't "playable" from anywhere in the app.

I.e. If you play a song from playlist X and then navigate to playlist Y there is no way to start that song without first simulating the navigation back to playlist X and bearing in mind the playlist could be the "I'm feeling lucky" playlist (or something similar) there is simply no way to implement such functionality.

The "remember what page I am on" functionality that we currently use is the closest we can get to this feature

**Comment by OOPMan** [comment]
I know this was closed a while ago but I was wondering...there must be some way to do this. The mobile app manages it? Do you think it uses an API that we don't know about? 

Maybe it would be possible by saving the current queue to a specially named playlist and re-loading from that when the application is restarted?

To be honest, the lack of this feature is a little glaring, it's just about the only bad thing about this piece of software...

**Comment by jostrander** [comment]
Feel free to take it up with Google. We have to pick and choose which features to implement based on what's possible, and what's feasible to maintain. This just isn't something that's feasible to try and figure out due to the complexity of the way Google's web interface works. If you find a bullet proof way to do this feel free to make a PR and we'll gladly look at it.
