### ISSUE TITLE
Feature Request: Add Side Letter Links to Jump to a Specific Library Section

### ISSUE THREAD

**Issue by pauloewerton** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1135]
Hi There!

It would be nice to have those side links to jump directly to a section of the music collection. The way Google Music default interface is right now obligates those who have large libraries to use the search bar to play what they want because browsing their list of artists/albums/songs is cumbersome and inefficient. I think that would be a great addition to GPMDP. Something similar can be found in the unofficial GMusic player for iOS. Thanks!

**Comment by jostrander** [comment]
Can you link to the unofficial player for iOS?

**Comment by pauloewerton** [comment]
Sure, here it is: https://itunes.apple.com/br/app/gmusic-music-player-for-google/id708727021?mt=8

**Comment by MarshallOfSound** [comment]
@pauloewerton Unfortunately due to the way GPM renders song tables this is currently impossible.

In order to save RAM GPM only renders 31 rows of a song table at any given time.  This means it is impossible for us to know where to send the user if they click "C".  Until google change their rendering policy or we find a way to accurately scroll the user to a specific location, this is getting the unfortunate wontfix tag :cry:

**Comment by pauloewerton** [comment]
Thank you for seeing this through.
