### ISSUE TITLE
Windows 10 animations

### ISSUE THREAD

**Issue by kybarg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#12]
Version 1.6 brought up better looking frame, but minimize/maximize animation isn't working now.

**Comment by MarshallOfSound** [comment]
I am aware of this issue, (not really an issue actually more of a style change).

It is due to the `FormBorderStyle.None` property that is set to customize the window frame.  Unfortunately the animation is due to the "default" / "standard" window frame and isn't actually a result of calling minimise on the form.

The only way to make the animation work again is something to do with `WinProc` calls.  I'll look into this but no promises.  C# is hardly by language of choice

**Comment by kybarg** [comment]
Hope this might help https://github.com/Soundnode/soundnode-app

**Comment by MarshallOfSound** [comment]
@kybarg Unfortunately not, that app linked is written in node (javascript).  The framework behind it might be more helpful, I'll keep looking around
