### ISSUE TITLE
Trojan/Mallware detection

### ISSUE THREAD

**Issue by Pixelstudio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1232]
**OS:**
All

**Issue Descriptions:**
Trojan / mallware detected.

**Steps to Reproduce:**
I'v download & installed the latest version, at that time our network guy contact me.
After installing and running he got a firewall warning that a Trojan was detected "Torpig"
Before that (when i downloaded it) he got a mallware detection.

So perhaps something got infected.. ?

**Comment by MarshallOfSound** [comment]
It is a false positive.  Many open source applications are affected by this as they are relatively unknown installers.

https://github.com/electron/windows-installer/issues/106#issuecomment-226613329

It is detected as a Trojan because they way we install (no admin permissions required) is considered suspicious by really strict AV and Firewall tools.

Just to reiterate, this is a false positive and there is nothing I can do to make it go away.  However, you can.  If you AV or Firewall has the ability to mark as a false positive, please do so.  If enough people flag our installer as a false positive eventually people will stop getting these warnings.

Cheers 😆
