### ISSUE TITLE
Show/hide appliaction to tray icon

### ISSUE THREAD

**Issue by francma** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1269]
**OS:**
Linux with i3wm (tilling WM) and i3bar

**Application Version:**
3.3.0

**Issue Descriptions:**
Show/hide option from tray icon menu doesn't work. It always says "show" despite fact it's already shown. Double clicking tray icon and closing application does nothing.

I tested it with similar electron app (twolfson/google-music-electron) and it worked (so it's not WM or Electron issue) -- clicking icon toggles shown/hidden (same with tray icon menu option). Maybe option "Close to Tray" would do the trick (since there is no minimize in tilling WM).

Thanks :)

**Comment by MarshallOfSound** [comment]
> Show/hide option from tray icon menu doesn't work. It always says "show" despite fact it's already shown. 

This is intended behaviour and in fact no one has ever considered this an issue before.  The button "shows" the player, whether the player is shown or not is not releveant.  I don't consider that a bug?

> Double clicking tray icon and closing application does nothing. 

Can you clarify what you mean here.  There was a massive thread a while ago where a conclusion was reached that on linux a double click should be a noop and a single click should toggle the window.

> I tested it with similar electron app (twolfson/google-music-electron) and it worked (so it's not WM or Electron issue)

Everything you have described comes down to individual implementation, all the buttons and click actions we handle manually and it is down to the application to handle them and respond as it sees fit.  Just because one electron app does something (twolfsen) doesn't mean another will 😄 

> Maybe option "Close to Tray" would do the trick (since there is no minimize in tilling WM).

This exists, have you tried clicking the close button on the window 😆   By default it will minimize to tray unless you turn that feature off in settings

**Comment by francma** [comment]
Single clicking doesn't work too. Closing application does nothing like I already said.

The thing is there is no minimize or close button in tilling WMs (it sends close via command). However, I haven't had any problems with other apps yet.

**Comment by MarshallOfSound** [comment]
> Closing application does nothing like I already said.

When you close the window through a command do you know if it is sending a close window command or a quit application command?

If it sends a close window command then it would minimize to system tray, if it sends a quit command it would quit the entire application.

This application was never designed with tiling window managers in mind and I personally have never used one so I'm not familiar with usage or expected actions.

**Comment by francma** [comment]
This issue is similar to https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/270.

The difference between gpmdp and twolfson is that they are calling window.hide() instead of window.minimize(), which is ignored on WMs without minimize (?? I don't know anything about Electron).

**Comment by MarshallOfSound** [comment]
Hmmmm, I could do a `WindowManager.getWindowManagerName()` to determine if we are using I3 and call `hide` instead of `minimize` if we are.

The problem is we want to call `minimize` on most other platforms for the minimize animation.
