### ISSUE TITLE
Broken Linux RPM 64-bit Download Links

### ISSUE THREAD

**Issue by blakejohnson86** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1282]
**OS:** Any

**Browser:** Firefox (Linux, Windows), Gnome Web (Linux)

**Issue Descriptions:** The Linux RPM 64-bit download link on the website do not work.  Windows and Mac, and the other Linux downloads work as expected.

**Steps to Reproduce:** Click on the RPM 64-bit Linux download link and nothing downloads.

**Comment by jostrander** [comment]
@MarshallOfSound it's because the package arch for fedora was changed from amd64 to x86_64, so now your regex matching of the releases is failing. 

Thanks for the issue report @blakejohnson86, if you still need a working link here is the releases page:

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases
