### ISSUE TITLE
Javascript error ocurred in the main process (v 3.3.0)

### ISSUE THREAD

**Issue by Kaitiff** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1331]
**OS:**
Windows 7 x64 SP1
**Issue Descriptions:**
Yesterday was working great, but today shows this error:
![image](https://cloud.githubusercontent.com/assets/1208628/16946539/62c0d838-4daa-11e6-9001-7e9b4d1b3ab9.png)
Tried to reinstall it deleting everything, but it keeps appearing
**Steps to Reproduce:**
Just make a fresh install, when program tries to boot, it appears.

**Comment by MarshallOfSound** [comment]
Just as a pointer for when other people read this.  **Steps to Reproduce** shouldn't be "install app watch error" because if I perform those steps the error doesn't appear (no way would I ship an app that does that).  Spend a bit of time trying to figure out whats wrong or at least look through past issues with the same name / reason.

#1319
#1325

> Simply go to %APPDATA%/Google Play Music Desktop Player/json_store and delete the .settings.json file.
