### ISSUE TITLE
Allow the 5 Star Rating system

### ISSUE THREAD

**Issue by zacjanes** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1355]
Just a request to include an option to turn on the following tampermonkey script to include displaying star ratings:
https://www.reddit.com/r/googlemusic/comments/3h0fwa/script_to_restore_5star_rating_system/

There's also a chrome extension which includes this ability: https://chrome.google.com/webstore/detail/prime-player-for-google-p/npngaakpdgeaajbnidkkginekmnaejbi?hl=en

I think it would be super handy. You would also get a whole heap more users as evidenced by the discussion on this here: https://productforums.google.com/forum/#!topic/play/HwKmVF5N5YA

**Comment by MarshallOfSound** [comment]
Duplicate #584

TLDR: I'm not to going to offer an option for users to bypass / enable a feature Google chose to disable.  Especially when that feature could be deactivated / have bad side affects at any time

**Comment by Kline-** [comment]
@MarshallOfSound 

Any chance of revisiting this? I see that in #584 a local DB was suggested as a workaround to not directly meddling with server-side data Google could choose to entirely remove the next day. Support for the 5-star rating system is the only thing that keeps me still attached to the official web player for anything.

The Google Play product thread linked in @zacjanes original request has been alive since May '15 and is still seeing more posts requesting the return of this feature even now in Jan '17.

**Comment by brentkelly** [comment]
+1 to this. There are sooooo many users requesting this, what is wrong with making it an option and letting the user choose if they want to risk any side effects? We are already making that decision in the chrome player with the tampermonkey script ...

**Comment by marek287** [comment]
+1
