### ISSUE TITLE
Miniplayer is tiny

### ISSUE THREAD

**Issue by adinklotz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#143]
Recently (I'm not sure exactly when), the miniplayer has been showing up much smaller than it used to, making it impractical and annoying to use.  See the attached image -- that's the normal Windows desktop, with the tiny mini-player.
To reproduce: just open the miniplayer with the arrow button at the bottom of the window.
I am on Windows 10, if that helps.
![minplayer](https://cloud.githubusercontent.com/assets/16441122/12281360/6618008c-b963-11e5-93a7-0643047f5be4.jpg)

**Comment by MarshallOfSound** [comment]
Do you have a 4K display?  Or DPI scaling turned on?

**Comment by MarshallOfSound** [comment]
If so:
Check out the builds below:  
[x86 Build](https://ci.appveyor.com/api/buildjobs/k169oa7gx74willf/artifacts/Google%20Play%20Music.Bootstrapper/bin/x86/Release/Google%20Play%20Music%20Desktop%20Player%20x86.exe)
[x64 Build](https://ci.appveyor.com/api/buildjobs/58g0xct0kkaty6fd/artifacts/Google%20Play%20Music.Bootstrapper/bin/x64/Release/Google%20Play%20Music%20Desktop%20Player%20x64.exe)

Hopefully these builds work perfectly :+1: 

Those builds are for the latest commits on master and should contain fixes for your issues

**Comment by adinklotz** [comment]
No. I have a normal HD display, and no special graphics settings enabled

**Comment by MarshallOfSound** [comment]
Have you tried one of the beta builds I linked, you have to uninstall your old version first.

**Comment by adinklotz** [comment]
I just installed the x64 build, and it works now!

**Comment by IrksomeZeus** [comment]
This issue is still occurring.
I have not had it happen before and there hasn't been a recent update.
The app was working fine yesterday, now today it is having this problem.
Completely closing the app and reopening it does not fix the issue.

I can drag the edge of the mini player to make it larger which fixes the issue; the new size of the mini player is persistent through a switch to the full player and back to mini and after completely closing the app and reopening it.

GPMDP v4.6.1
Windows 7 Enterprise x64
Monitor resolution: 1920x1200

![capture2](https://user-images.githubusercontent.com/10698732/46868537-a9d8b280-cdf6-11e8-8ef5-017ec90b4484.PNG)
