### ISSUE TITLE
Spinning icon that doesn't go away when starting the player

### ISSUE THREAD

**Issue by appetterson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1453]
**OS:**
Arch Linux stable - Up to date as of issue being raised

**Issue Descriptions:**
Last version I started getting an issue that if I tried to load anything the spinning loading icon came up and wouldn't go away. Now that is happening at launch so I can't play any music.

**Steps to Reproduce:**
Update to latest version and launch the player

**Comment by MarshallOfSound** [comment]
@appetterson I can guarantee you aren't on the latest version as this issue was fixed in `3.4.3`.

Arch linux builds aren't maintained by me or this repository and therefore I have no way to troubleshoot.  All I can say is try installing the `unstable` build from the AUR and ensure it is a clean install
