### ISSUE TITLE
Pages never load

### ISSUE THREAD

**Issue by galenasphaug** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1464]
**OS:**
Ubuntu 16.04 x64
**Issue Descriptions:**
Some pages will not load. The loading symbol keeps spinning.
If I use the Go to URL option, and go to my Music Library, the page loads but is not clickable. I have tried to run using `--disable-gpu`, but that didn't help.
I was already signed in when I noticed the issue. I also recently swapped out GPUs, but I don't think that matters.
**Steps to Reproduce:**
Launch the application
Wait
![screenshot from 2016-08-14 01-39-04](https://cloud.githubusercontent.com/assets/5401408/17648122/ef481f5e-61bf-11e6-8dbf-d75b2861fe03.png)

I might be the only one that is experiencing this, therefore it could be something with my own installation, etc. If any one has this same issue, or if you know how to fix it, please let me know.

**Comment by MarshallOfSound** [comment]
These issues are starting to annoy me now.

In order to create this issue you had to read this

> Hey There!
Thanks for taking the time to raise an issue.
Before you click that big tempting "Submit New Issue" button though, can you quickly run through the list below.

> * I have checked that there are no issues with similar or the same content

Did you just ignore that or decide to raise a new one for the lolz???

Please check the closed issues before raising new ones...

Duplice #1459 #1454 #1453 #1445
