### ISSUE TITLE
Feature request: try playing local files first

### ISSUE THREAD

**Issue by crispinb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1513]
**OS:**
OS X
**Issue Descriptions:**
It would be great to be able to point GPMDP to a local folder hierarchy, with the intention that if a mp3 matching the current play request is found there, it will be played locally as a first try.

This has (a) a certain logic to it given that Google Play Music can source (and match) tracks from local files, and (b) would be very helpful for those of us who live in slow/low-bandwidth parts of the world (ie. most of it as of mid 2016).

**Comment by jostrander** [comment]
While I commend the thought I'm not sure this is something that will ever be implemented in this project. There have been many requests for similar things such as offline music, playlists etc and the general consensus is that it's not possible and/or out of scope.

**Comment by crispinb** [comment]
That's a tad dismissive, especially given the only similar reference I've found has been to an issue that was closed without reason (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/932). No discussion or further questions re use cases or alternatives?

**Comment by jostrander** [comment]
I apologize if it seemed that way, my reasoning was stated in that thread as well though. It will add a lot of overhead in the player as it causes us to heavily rely on not only the DOM of GPM but also the internals of their JS. In order to play local files in their player we would need to override 100% of the functionality of Google play music. Its not as simple as pointing a audio tag to a local file and everything will just work.

**Comment by crispinb** [comment]
That expands usefully on "a lot of overhead" -- in effect a near-complete rewrite is a *lot* of overhead and I can see it would be unreasonable given the project's scope. Thanks.
