### ISSUE TITLE
Chromecast Audio Devices Misnamed

### ISSUE THREAD

**Issue by mknoell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1523]
**OS:** 
Windows 10 (v1607)

 **Issue Descriptions:**
List of "castable" devices is wrong. Here is a listing of the devices on my network (as seen by the chrome browse I am using to write this):

![2016-08-24 06_52_45-groove music](https://cloud.githubusercontent.com/assets/21219017/17929697/c43bddfe-69c7-11e6-94fb-93a5bc375de2.png)

However, in the app, when I attempt to cast - this is what appears:

![2016-08-24 06_43_58-start](https://cloud.githubusercontent.com/assets/21219017/17929679/a39be382-69c7-11e6-8e17-ba67d7e64427.png)

First it appears that the "." in the name of the device is causing the device name to truncate. In addition there is an incorrect number of devices listed - no idea were that's coming from. Interestingly, when select the correct "a" from the list, casting works.

**Steps to Reproduce:** 
Every time I go to cast it shows up. Maybe it's my naming convention (which differentiates video from audio casting devices) but this is the only place I have seen this naming disconnect.

**Comment by MarshallOfSound** [comment]
If I had to guess the reason our names are incorrect is because the name is passed from the MDNS local URI.

`.local.name.`

This is handled at an OS level by MDNS so using a `.` in the device name is actually against the MDNS spec.  Not much we can do to handle this apart from maybe figure out how to request the full device name once we find it.

Please raise this issue over at [`electron-chromecast`](https://github.com/GPMDP/electron-chromecast/issues) and if someone gets time they might look into it.  But I'm not sure why Google is setting invalid names in the first place.
