### ISSUE TITLE
Bluetooth headphones stopped working correctly with latest upgrade

### ISSUE THREAD

**Issue by marcgarciamarti** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1548]
Hello,

since the last upgrade, my bluetooth headphones won't work properly whereas Spotify or Skype do. Please, could you indicate what to provide in this specific case?

Thanks

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment]
We don't officially support Bluetooth headsets as it is impossible for an OSS project to get access to enough headsets to effectively support the multitude of different "standards" and intrerfaces.

If they worked with an older version they will probably start working again with a newer version.  It is probably caused by an upstream issue inside Chromium.  You're just going to have to wait this out 👍 

Sorry if that isn't very helpful but it's the best we can do 👍
