### ISSUE TITLE
Updating metadata songs

### ISSUE THREAD

**Issue by BertKrale** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1558]
Hey,

I'm a happy user of your Google-Play-Music-Desktop-Player on a windows 10 PC. It's a wonderful tool by using Google play Music.

I'm missing one function. Now it is able to update the tag information one by one by accepting the suggested information and  to save the new tag information.

With a lot of songs there is al lot of work to do if you want to update the metadata of several songs. It would be great if it is able to automatically update the information of all the songs or a selection of a number of songs.

Maybe it is possible to program this function on your program. It would be great,

Greetings,

Bert Krale

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Unfortunately this wouldn't be easy to implement. The data for all of that is abstracted far away into Google's code, and the Polymer (google's UI lib) doesn't make it any easier to do things like this. This is something we probably won't implement into this project because of the amount of time it would take to implement, if it's even feasible.
