### ISSUE TITLE
Feature Request: Middle Click to Add to Queue

### ISSUE THREAD

**Issue by AlexiG42** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1575]
Exactly what the title says - middle click a song, album, playlist or anything else, and it adds that to the queue.

I'm really sorry for posting this in issues and not in the proper section, but I'm new to GitHub and I don't know how to do it properly. Whenever I click on 'fork' and then 'pull request', I get an error that "MarshallOfSound:master and AlexiG42:master are identical". You're probably getting annoyed because it's obvious what the solution is, but it's not to me. It shouldn't be this hard to submit a feature request - why not just have a form on your website?

**Comment by MarshallOfSound** [comment]
> I'm really sorry for posting this in issues and not in the proper section, but I'm new to GitHub and I don't know how to do it properly.

Surprise 🎉 This is the correct section 👍 

> Whenever I click on 'fork' and then 'pull request', I get an error that "MarshallOfSound:master and AlexiG42:master are identical". 

Pull Requests are for code contributions.  Hence you can't PR two identical things as nothing would be added.

> Why not just have a form on your website?

Because if people can't go through the effort of signing up for a GH account then the issue / feature can't be all that important too them.  It weeds out the spam and troll posts as well as GH is fully managed and public.

> Feature Request: Middle Click to Add to Queue

As for the original request though, this is currently a "can't fix" as there is no known way to add an item to the queue with simulated UI interaction.  I.e. We have no way to trick google into adding this thing to the queue.
