### ISSUE TITLE
Port for mdns service is hardcoded, but possible to change service port via environment variable.

### ISSUE THREAD

**Issue by jostrander** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1598]
See #1595.

Which actually leads me into another issue, that the mdns broadcast is hardcoded.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/websocketAPI.js#L115

**Comment by MarshallOfSound** [comment]
And then because I love increasing the scope of problems.

The port is hardcoded in the remote app.

https://github.com/GPMDP/google-play-music-desktop-remote/blob/master/src/stores/WebSocketStore.js#L6

I would like to point out though that this environment variable was only really ever meant for testing purposes 😆
