### ISSUE TITLE
Feature Request: Output current song to text file

### ISSUE THREAD

**Issue by steeben** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1610]
I know there is a json file that has the info in it, but it is really confusing to use it in streaming software like OBS. If there was a file that simply had "Artist - Song Name" and nothing else, it would be really helpful for people that want to display that information on stream.

**Comment by jostrander** [comment]
I don't stream but I can see how this would be nice.  I think we could possibly add a text field in settings with variables so it can be configured. Ultimately up to Marshall of sound, and if accepted it would be blocked until he's finished rewriting the settings panel into react.

**Comment by MarshallOfSound** [comment]
In the past I have declined this request for the following reason.

The important thing to see here is that I offer an API, I don't offer integrations with streaming providers or screensavers or a whole bunch of other stuff people have asked for over time.  That's because at it's core an API offers data, not a service.

This means that if people want a text file they should read data from the API and output it themselves 👍 .  In Node.JS this is ridiculously easy

```js
watch('/path/to/json/file', (fileContent) => {
  const data = JSON.parse(fileContent);
  fs.writeFile('path/to/output', data.track.title + ' - ' + data.track.artist);
});
```

Literally 4 lines of code. 😆 

I'll think about this for a while because I kind of like the idea 
>  think we could possibly add a text field in settings with variables so it can be configured. 

But also 
> it would be blocked until he's finished rewriting the settings panel into react.

**Comment by MarshallOfSound** [comment]
Closing this out as https://github.com/GPMDP/gpmdp-plugin-now-playing-text-file now exists.  Just need to finalize plugin support post `v4`
