### ISSUE TITLE
Update loop after installing newest version

### ISSUE THREAD

**Issue by collinjackson93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#166]
I installed the new release today, but every time I open the application, it still prompts me to install the latest version. I think #164 is experiencing the same issue, as well. I tried rebooting, then uninstalling and reinstalling and I still encounter the issue. When I run the installer, it gives me the option to uninstall, instead of installing, so I'm pretty sure I actually have the latest version. I'm running 64-bit Windows 10.

**Comment by uhh186** [comment]
I had this issue too. I went to control panel/programs and features to uninstall to reinstall, but I noticed I had two entries for the program: one for the previous version and one for the new. So, I uninstalled them both, and now, when I try to run the installer for the latest version, it only gives me the option to "Uninstall," which fails because the source files have already been removed (It can't find the installation .msi"

**Comment by collinjackson93** [comment]
I hadn't noticed that. I checked on my system and found that I actually have 3 entries.

![image](https://cloud.githubusercontent.com/assets/5580739/12722474/b783cf98-c8ca-11e5-869f-6fb05945f6e3.png)

**Comment by mcarver2000** [comment]
That is because the file is for version 2.0.2 and not 2.10.  Checking the properties of the download show it is version 2.0.2

**Comment by uhh186** [comment]
Yeah, the 2.10 download is apparently downloading 2.0.2. 

Still can't get anything to reinstall though...

**Comment by collinjackson93** [comment]
I just checked both the x86 and x64 executables for 2.1.0 and they both show as 2.0.2.

**Comment by collinjackson93** [comment]
@uhh186 have you tried manually deleting the `C:\Program Files\GPMDP` directory? If that doesn't solve the problem, then you might want to open a separate issue.

**Comment by uhh186** [comment]
No, they uninstall the actual files just fine, there's something with uninstaller/installer that makes it think it hasn't been uninstalled, so it tries to uninstall, but can't because there's nothing to uninstall. When the 2.1.0 exe gets uploaded it should install fine since it's an update, so I think it's a problem with 2.0.2.

**Comment by MarshallOfSound** [comment]
OK guys, I screwed up here, I'll be pushing out another update shortly

**Comment by MarshallOfSound** [comment]
For those interested, I only version bumped the internal version number, not the actual MSI version number.  So it was getting quite confused as to whether it had updated or not.

**Comment by MarshallOfSound** [comment]
Can you guys all please let me know if you still experience the issue after update

**Comment by collinjackson93** [comment]
I just tested and it's working fine for me, which is why I closed the issue.

**Comment by MarshallOfSound** [comment]
@collinjackson93 Epic response time, I had barely published the thing and it was closed.  Thanks mate

**Comment by collinjackson93** [comment]
Thank you for resolving the issue so quickly!

**Comment by MarshallOfSound** [comment]
Yeah, I should really get out of the habit of pushing a release and going to bed, it means theres like an 8 hour gap till I hear about the issues.  But I do try and resolve stuff quickly #gottakeeptheconsumershappy :+1:

**Comment by uhh186** [comment]
The update fixes all the problems. Thanks again for all your work MarshallofSound, this app is a godsend and I love everything about it. Keep up the good work!
