### ISSUE TITLE
Feature request: Option to remove tray icon

### ISSUE THREAD

**Issue by mackuz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1661]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
The Player is great and smooth.
I'm happy to see, that there is a link on this player in Ubuntu's Sound menu. And as I allready have this link, it would be great to have ability to remove Player's icon from Ubuntu tray.

**Steps to Reproduce:**

**Comment by berryelectronics** [comment]
#636 #300 .

**Comment by jostrander** [comment]
Unfortunately in the near future removing the tray icon just won't be possible as stated in those issues. There is core functionality that would break by removing it at the current time.

**Comment by relgames** [comment]
First of all, thanks for the great app. I used to run Radiant Player, but it does not support controls from my BT headphones. 

There is a feature which I miss though. As you can guess, it's about the tray icon.
Before you send me into funny places, I must say I've read through all tray icon issues and I still don't understand what core functionality you are referring to.

There is one use case which does make sense: if a main window is closed and there is no task bar icon and then a user goes to settings and disables a tray icon as well, then there is no way to close the app or bring back the main window.

There is a solution: don't allow to hide a tray icon if task bar icon is hidden at the moment. It should be a switch on Windows, not checkboxes.

Are there other issues? Sorry, it's hard to gather a proper information because most issues just say "discussed before, closing" with no links to what exactly what discussed. I spent 30 minutes going in circles between those issues and the only issue I understood is the one described above, which can be solved.

Apologies if there is a single place with all issues and I just missed it. I checked FAQ and there is nothing about the tray icon.
