### ISSUE TITLE
Unable to control GPMDP with Bluetooth headphones

### ISSUE THREAD

**Issue by Mnkras** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1760]
**OS:**
macOS 10.12 (16A323)
Version 3.6.0 (3.6.0)

**Issue Descriptions:**
When using bluetooth headphones with media controls I am unable to pause/resume/next track/previous track

Media keys on the computer itself do work to control media.

**Steps to Reproduce:**
Have Bluetooth headphones that allow control of music players
Attempt to use controls to control GPMDP
Nothing happens

**Comment by MarshallOfSound** [comment]
Welcome to the world of macOS where the bluetooth stack is non-standard and there is nothing I can do about this 😢 

Because macOS doesn't send the buttons as play / pause events I can't do much to fix this.  You could subscribe to the bug report to apple regarding this but I think it is for registered developers only and has been open for years so 😢

**Comment by Mnkras** [comment]
Thanks for the quick response!
Would you mind linking/sending me the developer report id/title?

(PS, with some basic searching I found https://github.com/jguice/mac-bt-headset-fix which ill give a try)

Thanks

**Comment by edking4967** [comment]
@MarshallOfSound, do you know how Spotify handles it? I'd be interested in trying to work on this if you could point me in the right direction.

**Comment by MarshallOfSound** [comment]
@edking4967 Not a clue 😆
