### ISSUE TITLE
Audio Device Selection not working

### ISSUE THREAD

**Issue by vandepoelm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1773]
Windows 10

Audio Device Selection not working

if i select another audio device in the options or via the taskbar, the audio just continue to play via the default audio device.

using version 3.6.0

btw, i love the app, keep up the good work!

**Comment by berryelectronics** [comment]
PLEASE look at the closed issues first. Fixed in master. Will be out with 4.0.0

From #1770

Quote from #1769:

These are starting to annoy me now. This is fixed in master and will be out next release.

See these duplicates that you should have found before raising this issue:
#1761 #1755 #1722 #1714 #1707
