### ISSUE TITLE
Suppress update dialog until the album ends

### ISSUE THREAD

**Issue by paulcbetts** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1804]
Never show the update dialog while music is currently playing, wait until the end of the album ✨ ✨ ✨ ✨

**Comment by jimmyt86** [comment]
I had the mini player open when the update message poped up. I had to kill the app as there was no way to clsoe the notification. Minor issue with an easy work around.
![image](https://cloud.githubusercontent.com/assets/7913486/19713491/432e69be-9b92-11e6-8dbc-5639e05a3cf1.png)

**Comment by MarshallOfSound** [comment]
@jimmyt86 Looks like you were back on `3.5.0` when you got the update (I can tell from the transparent bar at the top of the mini player).  This issue was fixed in an update between `3.4.0` and `4.0.1` (can't remember which).  Please be wary of hijacking issues 👍 

For instance #1817 (quite a recent issue) is exactly what you just posted in this unrelated issues 😄

**Comment by jimmyt86** [comment]
Thanks @MarshallOfSound. I checked, but I didn't realise there was a closed ticket filtered out. This seemed related, as the popup appeared mid song.  Glad to see it's already fixed :)

**Comment by MarshallOfSound** [comment]
I totally forgot this was here.  I just pushed a change to the `UpdateModal` that will prevent the modal from being displayed again for an entire day after clicking "Not Now".  I don't feel as though the application should update without giving any warning or feedback so the modal has to appear at least once IMO.

This change should stop the modal being annoying 👍
