### ISSUE TITLE
Multiple monitor player not visible if monitor becomes unavailable

### ISSUE THREAD

**Issue by ddunngh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1811]
**OS:**
Windows 10 Home

**Issue Descriptions:**
I have two external monitors connected to my laptop.  One of the monitors sometimes will not recover from sleep mode and will have to be unplugged for a minute or two before being plugged in and recognized by the OS again.

If the Player is showing on that monitor when this power issue occurs and I log into the laptop the Player remains in that location on the non-existent monitor.  Most applications that I have (there are a few exceptions) 'sense' this change and shift their windows to an existing screen.

I'm guessing that the window's .Left value becomes a really negative number.  But I'm not sure.

**Steps to Reproduce:**
Not entirely sure because the external monitor issue seems to be a hardware 'handshake' issue that your computer might not exhibit.

**Comment by MarshallOfSound** [comment]
> If the Player is showing on that monitor when this power issue occurs 

This is due to two different methodologies of detecting monitors.  Lot's of application use an observer methodology where they constantly check that the current location is valid.

Electron provides events for `display-added` and `display-removed`, if your monitor is not cleanly removed it probably isn't firing those events so there isn't much we can do about it 😢 

If you relaunch GPMDP though it should detect the new monitor layout correctly and fix the position
