### ISSUE TITLE
Thumbs up does not 'love' the track on last.fm

### ISSUE THREAD

**Issue by cristianmtr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1830]
**OS:**

Windows 7

**Issue Descriptions:**

Thumbs up in GPMDP does not 'love' the track on last.fm

**Steps to Reproduce:**
- Listen to song. 
- Press the 'thumbs up' button
- Look at last.fm profile: song is not 'loved'

**Comment by MarshallOfSound** [comment]
This is the complete opposite of #1799

Be aware it only works if you thumbs up / down the song from the player bar at the bottom.  Liking / unliking a track in a playlist or the queue or such doesn't fire the love event

**Comment by cristianmtr** [comment]
Tried it again just now, doesn't work

**Comment by MarshallOfSound** [comment]
@cristianmtr Is it scrobbling that song successfully?

**Comment by cristianmtr** [comment]
Yes, it is.

**Comment by cristianmtr** [comment]
Nobody else seeing this issue? What am I missing here?

**Comment by cristianmtr** [comment]
Tried it on multiple machines, still doesn't work.

**Comment by ronilaukkarinen** [comment]
Same here, not working.

**Comment by MarshallOfSound** [comment]
I swear it's working for me, I'll reopen and investigate

**Comment by ronilaukkarinen** [comment]
Sorry, forgot my details.

**System:** Mac OS X: 10.11.6 (El Capitan)
**App:** V4.0.3 (via website)

Fresh install, just found your app (great progress by the way!). Last.fm scrobbles just fine, but thumbs up won't sync to loved, tried many songs. I hope this helps.

**Comment by Niklan** [comment]
*System:* KDE Neon (Ubuntu 16.04 i believe udner hood).
*App:* v4.0.X (where is Pirate language was added, i don't find whre app version is printed).

Same here. Thumb up via bottom panels not trigger like on Last.fm.

P.s. Also, it will be great to have setting for minimum track playback for add to statistic of last.fm. I see some delay is set, but it is not clear. What % of track, or seconds must play before scrobble is counting?

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/4f810e3ac12030dbddc498f3f6d868396c0e72fe/src/renderer/windows/GPMWebView/playback/handler.js#L54

I found that 50% is required to get scrobbled and 10 second before previous scrobble, but it's not true, i think, tracks which not reach 50% also scrobbled.

**Comment by MarshallOfSound** [comment]
> but it's not true, i think, tracks which not reach 50% also scrobbled.

Not sure what you mean here but the implementation is exactly following the spec in the last.fm API docs

**Comment by csc0tt** [comment]
I just downloaded and installed this today (Windows v4.2.0) and tried using the thumbs up button in the bottom bar and, I didn't see the love on last.fm. However, I did see a duplicate track being scrobbled for two different songs I tried thumbs upping. One was already thumbs up'd and I clicked it off and back on, the other wasn't set yet and I clicked the thumbs up.

When I refreshed my profile later after the next song (to make sure it wasn't duplicating other songs) that I didn't touch the thumbs for, I noticed they were gone. Maybe last.fm removed them because the timing wouldn't make it possible for me to have listened to both?

**Comment by jkcclemens** [comment]
I was listening to the track "Lone Digger" and I hit the thumbs up icon, which resulted in 

![this](http://i.imgur.com/6e4KcM1.png)

"Comics" is the next song on the album, which I started listening to after "Lone Digger."

I've never experienced hitting thumbs up in GPMDP loving the song on last.fm. I would love for this to be an option under the last.fm settings and for it to be fixed.

**Comment by exhuma** [comment]
I just realised that this is not working for me either. I could have sworn this worked in the past (maybe this was disabled due to #1799? But maybe I'm mixing this up with a GPlay Chrome extension I had before GPMDP)

I quite like to look at both the recomendations from Last.FM *and* GPlay. This kind of stumped me. I just realised that I may have lost quite a lot of "loves" because of this.
