### ISSUE TITLE
Request: Light mode theming + misc. 

### ISSUE THREAD

**Issue by FlyingGoats** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#184]
Thanks for all the great work you've done so far, really looking forward to the 3.0 release.

I've got a few feature requests. I'm not sure how feasible these are, but given the changes in the dark theme think they are able to be accomplished.

1. Primary color theming in light mode (Eg. Blue primary in attached screenshot)
2. Move back/forward  nav arrows to left of search bar to be more consistent with Windows Explorer, most web browsers, etc (Muscle memory).
3. Remove thin orange border around window.

Please see the attached image.

![gpm theme update](https://cloud.githubusercontent.com/assets/17249361/13046934/61fc31ec-d427-11e5-80d8-20a387dcdaa8.jpg)

I realize requests 2 & 3 are mainly personal preference.  I think 1 would be nice to have for many users however.

Once again, thanks and all the best.

Luke

**Comment by MarshallOfSound** [comment]
OK, so number 2 is `Fixed in 3.0.0`
Number 3 simply isn't going to happen (many reasons here but mostly its keeping an obvious boundary between the app and a potentially white background app

Can you re raise number 1 on this repo https://github.com/gmusic-utils/gmusic-theme.js with that screenshot.  It might be possible but it is not a small change.  The current theming library treats the header (the bit behind the search box) as the background rather than the highlight color.
