### ISSUE TITLE
Over 900MB RAM usage

### ISSUE THREAD

**Issue by akarki15** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1877]
**OS:**
MacOS Version 10.12

**Machine:** 
MacBook Pro (Retina, 15-inch, Mid 2015)
2.5 GHz Intel Core i7
16 GB 1600 MHz DDR3

**Issue Descriptions:**
This app consistently takes up >900MB ram. This is comparable to entire chrome app that has >10 tabs. Is this normal? Can we memory profile this app on a mac and see if there are ways to minimize the memory usage.

**Steps to Reproduce:**
Run it on a mac.

![image](https://cloud.githubusercontent.com/assets/3751173/20066259/f012861a-a4de-11e6-8369-9215abd48467.png)

**Comment by JaKXz** [comment]
I'm seeing this issue on OS X 11.6 (El Capitan) as well. I'm not sure how much value there is in actually debugging the perf issues vs. the amount of time it might take. That being said, if the issues can be found and fixed easily, please do so :)

My proposal instead would be to offer a "low res" or basic mode option, that only shows a list (no expensive graphics or visualizations) of what's playing and what's coming up.

**Comment by MarshallOfSound** [comment]
> This app consistently takes up >900MB ram. This is comparable to entire chrome app that has >10 tabs. Is this normal?

No this isn't normal.  But in answer to the coming question "What can I do about it?".

Nothing.  There is absolutely nothing you or I can do about this RAM usage because (at least from the screenshot you provided) it is being caused by GPM not by my code.  Those helper processes run the GPM site itself.  If I had to guess you have a largish playlist collection and google is caching stupidly large object lots of times.

The best I can suggest is to relaunch the player every now and again.  That and to cross your fingers that the resource usage improvements of Chromium 54 will help this when they hit Electron `1.5` 👍 

Sorry 😢

**Comment by stillie** [comment]
is this issue also on the windows version of the app? I am getting over a gig of mem usage when using the app? This causes the music to start lagging out then the app starts freezing and slows down drastically?
