### ISSUE TITLE
Player crash with OSX notification song

### ISSUE THREAD

**Issue by mthchz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1878]
**OS:**
Mac OSX El Captain 10.11.6
Google Play Music Desktop version 4.0.2

**Issue Descriptions:**
Player crash when a OSX notification (with song) is recieved. The app must be quit (+Q) and relaunch to listen music. 

**Steps to Reproduce:**
1- Launch any song in Google Play Music Desktop
2- Get notification, with song, from an app. Each time with Mail and Message in my case.

**Comment by MarshallOfSound** [comment]
I'm not sure I understand the issue.  Is this caused by notifications from other apps?

**Comment by mthchz** [comment]
Exact!

When I having a notification from other app (Mail or Message), with notification song, the player crash and must be relauch. 
But without (desactivate song from app preference) there are no problem.

**Comment by MarshallOfSound** [comment]
@mthchz I can't reproduce this issue on any of the macOS machines I have access to.  Do you perhaps have some kind of custom notification interceptor set up or a fancy window manager on macOS?

**Comment by MarshallOfSound** [comment]
This would appear to be an issue at the hardware / driver level with your audio output on your mac.  I can't reproduce the issue and I have tried on a few different macOS devices.  I would suggest either disabling the tone or attempting to discover the root cause of the crash by analyzing the system logs on macOS.

There isn't much we can do about this on the GPMDP side of things I'm afraid 👍

**Comment by mthchz** [comment]
Don't worry, thank you for your support!
I'll follow your recommandation, and try to debug on my machin.
