### ISSUE TITLE
Please add a hotkey for play (not toggle play)

### ISSUE THREAD

**Issue by KruyKaze** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1944]
Meaning if music is already playing, keep playing in stead of pausing playback.
Thanks a lot.

**Comment by Alipoodle** [comment]
Why do you want it to just Play and not Toggle play?

**Comment by KruyKaze** [comment]
I have the pc setup "hit play" at certain times. And I don't want it to stop the playback if music is already playing. 
Thanks

**Comment by MarshallOfSound** [comment]
I don't see the need for this.  It would literally be adding a hotkey with **less** functionality that one that already exists.  For your use case (as strange as it sounds to me) you should probably use the `PlaybackAPI` instead of simulating hotkeys.

If you really want to keep simulating hotkeys you can use the stop hotkey following by the play/pause hotkey.

I'm gonna have to put this one as a `wontfix`

**Comment by KruyKaze** [comment]
Could you point me to that playbackapi ? I couldn't find it.
Thanks again.

**Comment by MarshallOfSound** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md

**Comment by RedGearPro** [comment]
Hi, I would like this to be reopened. My bluetoothe headset (and many others) give a xf86audiopause and xf86audioplay when pressed. Google play music desktop does not respond to these keys.

**Comment by jostrander** [comment]
I believe this is the wrong thread for that particular issue.

**Comment by jostrander** [comment]
However with the refactor of the app, this would actually be a simple drop in to get working, if someone were to PR it I'd probably nudge @MarshallOfSound into accepting it. I understand the need for a hotkey like this as I've been in situations were you have multiple hot keys fired for automation and you want things to be idempotent.
