### ISSUE TITLE
Very high CPU usage when not minimized

### ISSUE THREAD

**Issue by vvuk** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1947]
Windows 10 -- if the full player window is visible, it uses an *extremely* high amount of CPU -- two processes each at ~10-15% of CPU.  Note that 12% is "one full core":

![2016-11-22 11_14_54-task manager](https://cloud.githubusercontent.com/assets/194965/20531508/015d8a42-b0a5-11e6-9e3b-322198b481a5.png)

The mini player is better -- one busy process at ~5% and another at 1-2%.  But that's still not great, especially given that the mini player is a 100% static image unless you hover over it.

Minimized, the player uses <=1% (the main process at ~1%, the others at 0%).  The process that's using the CPU is the main process (not the chromium renderer processes).

**Comment by MarshallOfSound** [comment]
@vvuk There isn't much I can do about this.  I have optimized as much code as I feasibly can.

And FWIW 12% CPU usage does not equate to an entire core.

High CPU usage is a side-effect of Googles animation and material focused UI.  There is nothing I can do to make it better.

Also FWIW 

>The mini player is better -- one busy process at ~5% and another at 1-2%

Is incorrect, the mini player behind the scenes is actually the full player with an image overlaid on top.

**Comment by vvuk** [comment]
> @vvuk There isn't much I can do about this. I have optimized as much code as I feasibly can.
> And FWIW 12% CPU usage does not equate to an entire core.

It.. does; viewing CPU usage by core shows one core spiked as well.

>High CPU usage is a side-effect of Googles animation and material focused UI. There is nothing I can do to make it better.

Hmm.. running the same UI in Chrome itself shows CPU usage to be <2%.  It could be something about the additional html/css/event handlers/etc. that the overlay UI adds.

>Also FWIW
>>  The mini player is better -- one busy process at ~5% and another at 1-2%
>
>Is incorrect, the mini player behind the scenes is actually the full player with an image overlaid on top.

I'm not sure what you mean by "is incorrect" -- that's the behaviour that I observe.  The image overlaid on top causes the rendering engine to skip doing a lot of work for elements that are not visible, so perhaps that's a good place to look for performance wins.

But, it's certainly fair to be uninterested in fixing this! I may take a look when I have time.

**Comment by JP-Ellis** [comment]
I can report the same issue on Linux, with GPMDP's CPU usage being about 150% (note that 100% equates to 1 core being fully used).

![screenshot from 2016-12-20 15-18-18](https://cloud.githubusercontent.com/assets/3196162/21338154/971fd9b2-c6c7-11e6-9f0a-35f138c0f910.png)

When minimized, the usage goes down to about 4%

**Comment by deeprave** [comment]
I am reporting the same issue on an MBP mid-2014 suing both macOS Catalina and Mojave. Playing back or paused it is the same usage, so playback is not the issue. 125% of 400% over four cores, i.e. over 30% of available CPU on average.

By comparison, Amazon Music is not exactly lightweight uses almost no CPU at all. Apple Music (formerly iTunes) more heavyweight again uses virtually no CPU while running and it has a much more complex UI.

Sad, because this issue stops me using this app for anything but a "let's see if this issue is fixed" every couple weeks. I need the processing power and battery life for more serious stuff but would like to take advantage of my GM subscription on the device I use the most.

/d
