### ISSUE TITLE
No forward / back button? Background image artwork issues, music playing after closing

### ISSUE THREAD

**Issue by FlyingGoats** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#198]
Not sure if this was intentionally removed or a bug, but I get no forward / back buttons. 

Background image artwork when in dark theme doesn't get "cut off" when it should (Can make it hard to read text, see images attached, "top songs" text for instance).

![lightmode](https://cloud.githubusercontent.com/assets/17249361/13547301/28a77c54-e321-11e5-9529-ada317634662.jpg)
![darkmode](https://cloud.githubusercontent.com/assets/17249361/13547302/28aa50b4-e321-11e5-93c0-efea846554d6.jpg)

EDIT: Originally I had said music had continued to play after quitting the app from the system tray and could not stop it even after opening a new instance of the app. I'm not 100% sure what happened but for now I'm going to chalk it up to user error somehow, as it turned out the app *was* still running behind all windows but wasn't showing an active instance of it in windows task bar. Shrug. Will update if anything else funny happens.

I see the window border has gotten even bigger :( lol EDIT: Not sure if feature, bug, or serendipitous, but it's actually opening *minimized* but perfectly sized to hide the border haha. Oh well, if it works :P

Otherwise it seems to be running great! Thanks again

**Comment by MarshallOfSound** [comment]
OK, I've read this thing like 20 times and I'm still a bit confused with all the edits and such.  Can you comment again with a bullet point list of things that are broken / not what you think they should be.

**Comment by FlyingGoats** [comment]
Apologies for my rambling.

- Back / Forward buttons missing?
- Refer to images for difference in background image cutoff making text nigh-illegible (See "Top Songs" text)

Safely ignore the rest pending further usage.
Cheers.

**Comment by MarshallOfSound** [comment]
Back / Forward missing was a design decision based on a thread somewhere (which I will probably never find again) explaining that if you can't use a website without forward/back navigation buttons the website is doing something wrong. :+1: 

Bearing in mind that was on a google product forum I tried using GPMDP without the forward / back buttons and I managed suprisingly well.  I tried to use them for the first few days and after that not really :smile: 

As for the images, well, that's a funky side effect of the theming.  Could I possibly trouble you to raise that as an issue on the theming library https://github.com/gmusic-utils/gmusic-theme.js

**Comment by FlyingGoats** [comment]
Fair enough. I will personally miss them but I can somewhat agree with your conclusion.

I will certainly raise the theming issue.

**Comment by DougieNeish** [comment]
In response to the back/forward buttons - I like to use the feature because I can use the buttons on the side of my mouse. I find it quicker to navigate back to where I just was, and saves me an extra click.

**Comment by MarshallOfSound** [comment]
@DougieNeish Implementing the buttons on the side of your mouse I would consider slightly different and possibly a feature work implementing.  Is there a separate issue for that?  (I'm lost in my own issues section this morning)

**Comment by DougieNeish** [comment]
Not that I'm aware of.

**Comment by MarshallOfSound** [comment]
*winks*  Don't suppose *winks again* you could raise that one *winks for the third and final time*

**Comment by DougieNeish** [comment]
Just edited my post!

**Comment by MarshallOfSound** [comment]
:+1:

**Comment by eawutka** [comment]
It's correct that a website that you can't navigate without the back button is a poorly designed site, in the same way that a desktop app that you can't use without keyboard shortcuts is a poorly designed desktop app. Nobody is taking the keyboard shortcuts out of Photoshop, because for the people that are aware of them and enjoy using them, it makes the process so much faster and easier to navigate. For the people who aren't aware of them, the same options are available in an easier to find dropdown menu.

I think the best reasoning is the fact that the Google Play Music web app itself has support for the back and foward buttons. If it was such a bad idea, Google wouldn't have put it in.

I love your app, but I will be downgrading back to the previous version because I use keyboard shortcuts and my mouse buttons whenever possible. (well, also because none of the media buttons on my keyboard work in the new version, but that's probably just a bug.)
