### ISSUE TITLE
Audio stops abruptly and window content disappears

### ISSUE THREAD

**Issue by banduccm** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2010]
**OS:** Windows 7 SP1 x64

**Issue Descriptions:** At random, the GPMDP will cut audio and the window will go blank. It needs to be closed and restarted in order to function again.

**Steps to Reproduce:** I haven't noticed anything specific going on when audio cuts. I usually have Chrome, Visual Studio 2015, Outlook, and Skype running.

This issue seems to be new since 4.0.4. I have tried uninstalling and reinstalling fresh with both 4.0.4 and 4.0.5, but this has not fixed the issue.
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/647284/debug_info.zip)
![Screenshot](https://cloud.githubusercontent.com/assets/5399545/21117912/4254f238-c081-11e6-880d-2ff599faf4b5.png)
![Processes](https://cloud.githubusercontent.com/assets/5399545/21117925/555bb48e-c081-11e6-8ecd-a4429cdb0e08.png)

**Comment by MarshallOfSound** [comment]
> This issue seems to be new since 4.0.4

Although possible this is highly unlikely as that release contained just theming fixes AFAIK.

A black screen normally indicates the renderer has crashed which could be caused by any number of driver updates (normally graphics) and other things.  I'm currently designing a tool to help people diagnose these kinds of issues but until then there is nothing we can and with the upcoming bump to Chromium 54 this issue will likely go away anyway 👍
