### ISSUE TITLE
Prompt to enter password twice

### ISSUE THREAD

**Issue by the2003s** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2079]
steps to reproduce:

1. sign out of the app
2. click connect
3. enter username
4. enter password
5. (optional) i've got 2 step auth on my google account, so in this step I authorize the sign in
6. I'm being prompted to enter my password again and then I'm logged in

The main issue is that you have to enter your password twice in the above flow. It also makes me wonder of potential security issues. If possible, Oauth would be a better option in my opinion.

my system details:
Macbook pro 15"
MacOS sierra 10.12.2 (16C67)

**Comment by jostrander** [comment]
The entire application is based on the web interface, and there's nothing we can do to change how auth works, as that is all done by Google. We inject our scripts after the login is finished.

**Comment by sjaensch** [comment]
This is happening to me as well. Since it's the only web app that I use that has this problem I highly doubt it's an issue with Google (alone). I use my Google Account to sign into a multitude of services and apps and this one is the only one that has this problem. I'd be great if you could reconsider closing this issue and maybe instead audit the way you use the Google authentication API. Maybe there is a bug hidden there somewhere?

**Comment by MarshallOfSound** [comment]
We don't use any authentication API.  The login is handled entirely by GPM, we don't do anything until a GPM page loads so we have nothing to do with auth
