### ISSUE TITLE
On new install have to sign into google account twice

### ISSUE THREAD

**Issue by Sp4rkR4t** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2113]
**OS:** Windows 10 & Windows 7

**Issue Descriptions:** Whenever performing a new install when I enter my google email I then get asked for my password, then my 2fa code, and then once again for my password

**Steps to Reproduce:** 

Install app
Sign in (might require 2fa to be enabled on google account)
You will have to enter password a second time.

**Comment by jostrander** [comment]
As far as I'm aware there's nothing we can do about this. Our scripts don't modify the login sequence in any way, it's all provided straight from Google.

**Comment by vitch** [comment]
This is happening to me as well (and also in #2079) - not just on a new install but seemingly every time I log in.

You can understand people being nervous about entering their google password into a third party app - especially twice in a row!

I don't know what you might be able to do about this - I guess since you are just wrapping Google's code there is no option to do the login via OAuth?
