### ISSUE TITLE
Application freezes on playback

### ISSUE THREAD

**Issue by Virkkunen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2167]
**OS:**
Windows 10 version 1607

**Issue Descriptions:**
The application freezes a few seconds after starting music playback. The music still plays and media keys still respond, but the interface is stuck on whatever it was. Right clicking the icon on the notification tray to open its context menu will unfreeze the app, but only as long as the context menu is open. I cannot produce a debug zip since the whole app freezes. This happens on the 4.1.1 version.

**Steps to Reproduce:**
Play any song and wait a couple of seconds until the interface freezes.

**Comment by MarshallOfSound** [comment]
Disable notifications in the GPM settings, you are experiencing a windows bug.

**Comment by akj10** [comment]
I have been experiencing this issue in both Windows and Ubuntu since a few months, and was about to give up on the player. So glad I found this thread, it has solved the issue on Win10. Will check in Ubuntu next time I reboot!
It will be great if this information could be included in the description for Notifications. Would be helpful for the uninformed users :)

**Comment by MarshallOfSound** [comment]
@akj10 It's a really rare issue, maybe like 1/1000 (maybe even less than that) so putting information like that would scare more people into disabling it than it would help people who legitmately have the issue.  The top google result for "gpmdp freezing" is an issue thread with the same solution "disable notifications", so I think discoverability is just fine atm 👍

**Comment by akj10** [comment]
Sure!
I confirm that it helped on Ubuntu as well, I do not see the frequent freezes that I used to have earlier.
