### ISSUE TITLE
Mini-play controls vanish

### ISSUE THREAD

**Issue by TripyVOX** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2168]
**OS:** Windows 7

**Issue Descriptions:** The mini player controls vanish after minimizing

**Steps to Reproduce:** 1, turn on GPMDP 2, Use mini player 3, profit

**Comment by MarshallOfSound** [comment]
This is a windows redraw bug, toggle your "use system borders" setting

**Comment by TripyVOX** [comment]
Toggling System Borders does nothing to fix the issue.
This is a windows 7 system.

**Comment by ccolorado** [comment]
Same issue on Archlinux. 
There doesn't seem to be a way to return to the full player either. Killing the app is necessary to go back. 
Only hotkeys working, perhaps a hotkey to toggle between player modes could help.

**Comment by MarshallOfSound** [comment]
@ccolorado What version are you on?

**Comment by ccolorado** [comment]
Can't really tell from the application but I found out that it most be very outdated as I haven't switched to the new aur package on this computer.

**Comment by BrianAllred** [comment]
@ccolorado Make sure the issue doesn't appear using one of the new AUR packages (either gpmdp or gpmdp-git). If it does, report the issue on the AUR first. As the package maintainer, I try to keep @MarshallOfSound's Archlinux issue load down since he doesn't officially support it. I like to troubleshoot issues with users there before we decide to open upstream issues.

**Comment by ccolorado** [comment]
Thanks, turns out this computer was using the previous AUR (gpmd) package. Upgraded to the new one and the issue is no longer present. 
Thanks
