### ISSUE TITLE
Use mouse side buttons to navigate forward/back between pages

### ISSUE THREAD

**Issue by DougieNeish** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#224]
It would be nice to be able to navigate forwards/backwards between recent pages using the mouse side buttons (as seen in web browsers). A slightly different request to having forward/back buttons in the GUI.

**Comment by MightyPork** [comment]
I've done some research (read: googling), and it appears this is simply not possible with JavaScript - no event is fired when those buttons are pressed.

We will have to add buttons to the menubar (?).

**Comment by juschu** [comment]
Is GPMDP made with Electron? Or something similar?
At least it seems NodeJS is used and you can extend NodeJS with C/C++. Perhaps this way it would be possible to register those mouse button events.
And while vanilla JavaScript doesn't have events for those buttons, that doesn't mean that Electron (or the used framework) doesn't add these events to vanilla JavaScript.

**Comment by MightyPork** [comment]
juschu it doesn't add anything currently, I tried in the player itself.

**Comment by juschu** [comment]
At least NodeJS is adding the ability to extend JavaScript with C/C++. That's not possible in "normal JavaScript" in its native envoirement, the internet browser.
And when you can use C++ somthing like [this](https://msdn.microsoft.com/en-us/library/windows/desktop/gg153548%28v=vs.85%29.aspx) could be a posibility.
Of course that would be plattform specific. I took a look inside the source and found a <webview> tag with the attribute "nodeintegration". That smells like GitHub Electron. @MarshallOfSound: Am I rigth with Electron?
So the first approach should be to check if Electron can handle those Events, rather than implementing three different plattform specific solutions.

But for me the back functionality is essential. So I added a quick&dirty solution in app-3.0.0\resources\app\build\public_html\index.html
In the &lt;header&gt; I added
```
<div class="controls">
  <div id="history-back" onclick="historyBack()" class="control">
    <-
  </div>
  <div id="history-forward" onclick="historyForward()" class="control">
    ->
  </div>
</div>
```
And at the bottom in the last &lt;script&gt; I added
```
var webview = $("webview")[0];
function historyBack(){
  webview.goBack()
}
function historyForward(){
  webview.goForward()
}
```

I'm interestet in Electron anyway. So if it's really Electron and I find the time to learn it, perhaps I will implement the mouse button functionality too (and also make those back-/forward-buttons in the UI less ugly).

**Comment by MightyPork** [comment]
juschu btw we now have a back button implemented, it's on the master branch. See #348
support for those hardware buttons would be awesome though

**Comment by MightyPork** [comment]
it's windows only :(
but I suppose best we have with Electron currently...
