### ISSUE TITLE
Feature Request: Start minimized

### ISSUE THREAD

**Issue by KristupasSavickas** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2260]
It's annoying having 4 different programs pop up when the computer loads up, so I'd like to reduce that number to a minimum. One of those programs is GPMDP. There is an option to start the program when the computer starts, however, unlike many other programs that can do this, there is no option to start it minimized.

**Comment by hassanila97** [comment]
I second that. It's very nice to have it start on boot, but annoying to have to manually minimize at every boot. (Windows)

**Comment by fraserhaer** [comment]
@MarshallOfSound 

I'm going to give this one a go. It seems like auto-updater has an option for opening minimised so that makes it relatively simple. I've found the spot in GeneralTab to add the setting and I've added an en-US string in locales in the same way you've done other ToggleableOption settings.

I'm just not sure how to test it... how would I get my local dev build to open on launch?

**Comment by MarshallOfSound** [comment]
@fraserhaer You can't get your dev build to open on launch.  If you run `npm run package` though you can get the packaged version to open on launch 👍

**Comment by fraserhaer** [comment]
@MarshallOfSound Right after I said I'd do this I found out I'm moving from Mackay to Brisbane... I'll get back to this next week if no one else has done it before then.

**Comment by st33ly** [comment]
any updates on this?

**Comment by MarshallOfSound** [comment]
> any updates on this?

Top tip, updates / progress are normally posted on the issue ;). It's still up for grabs afaik

**Comment by snhardin** [comment]
Heads up! Since this is a feature that would be useful to me and it's been a while since fraserhaer has done anything with this, I'm gonna work on this one.

**Comment by MarshallOfSound** [comment]
Fixed in #2564
