### ISSUE TITLE
youtube video player broken

### ISSUE THREAD

**Issue by markuhub** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2302]
**OS:**
Windows 7 / Windows 10
**Issue Descriptions:**
YouTube video player does not play at all.
**Steps to Reproduce:**
1. Search a song.
2. Choose your video and click on it.  It opens the video player. 
3. Click play.
4. It doesn't play

Cheers.
![captura](https://cloud.githubusercontent.com/assets/26289719/23731835/5bf34bc0-0435-11e7-92a7-ecfa533434ba.PNG)

**Comment by MarshallOfSound** [comment]
Interesting, I can repro this I think.  Looking into it now 👍

**Comment by MarshallOfSound** [comment]
This appears to due to GPM only officially supporting latest Chrome which is now `57`.  Electron is currently based on `56` which means that this one method that GPM tries to use; `MediaSession.setActionHandler` is not available and it just gives up completely.

Upgrading Electron will fix this issue when we get to Chromium 57.  I tried to find a workaround but `MediaSession` can not be hacked around.  😢 

Marked as resolution upstream
