### ISSUE TITLE
Websockets restarts after every song

### ISSUE THREAD

**Issue by Pandovich** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2315]
Hello I made a simple script that outputs some song info into a file. I worked fine, but now it crashes after every song change with Websocket is closed error.

OS: Windows 10 (x64); Linux (x64)
Version: 4.2.0

Issue Descriptions:
When I change song /pause, skip, .../ websocket restarts. 
Error: "WebSocket connection is closed: code = 1009, no reason."

Steps to Reproduce:
Just skip song.

**Comment by jostrander** [comment]
Did this work fine with 4.1.1? I don't think anything changed in the web socket code that would cause this.

**Comment by Pandovich** [comment]
I tested it just now, but problem is still there. Last working version was around December 2016. Probably 4.0.x, not sure though.

**Comment by Pandovich** [comment]
I found the last working version. (4.0.1)

**Comment by jostrander** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/57213ab582b418f392c67582b3543e11b69f5840

This is the only thing I can find that _may_ have caused the web socket to stop working for you after 4.0.1.

**Comment by Pandovich** [comment]
This is the code I use: http://pastebin.com/VxbHcSFX  (Python 3, websockets, asyncio) but it doesn't include anything about version.

**Comment by jostrander** [comment]
Yeah I'm trying to figure out what caused the version bump myself. Maybe @MarshallOfSound can step in and help out here.

**Comment by lsweatman** [comment]
The only difference from the 4.0.2 websocketAPI.js and the 4.0.1 websocketAPI.js that is applicable is around line 140. 
![capture](https://cloud.githubusercontent.com/assets/20482967/24028241/a01e6d74-0a8a-11e7-8df1-322bc924a4b4.PNG)

**Comment by MarshallOfSound** [comment]
@jostrander The API bump was due to some change in `gmusic-ui.js` I think

Tbh I think what is happening here is you are using a websocket client that doesn't adhere to the spec and at some point a bump in our `ws` version (which is spec compliant) has caused your client to stop working.  The remote android app still works as it uses a spec-compliant websocket client so I would suggest seaking out an alternative websocket client.

Closing as an issue on the client end of things, if it turns out that I'm wrong about this 🌵 I shall reopen 😄
