### ISSUE TITLE
Feature Request: Write Current Song Info to .txt File

### ISSUE THREAD

**Issue by gch5074** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2329]
**OS:** Windows 10 x64

**Idea Descriptions:** I'm currently a streamer who's been using Spotify for a long time now, and I've been using a tool called Snip to gather the song info (title, artist, album, and album art [last one is unnecessary]) to put it on stream in the corner.  It gathers the info from Spotify and simply updates it any time Spotify changes tracks, which updates the stream text nearly instantly.  I just switched paid services to GPM, so there's no way currently for me to show the current track without it looking really bad.

I know this capability probably won't help too many people, but I'm completely new to Javascript and only have experience in Java (and only 2 courses of that in college).  If it helps, I'll gladly toss a couple bucks your way to support the project.

Thanks!

**Comment by MarshallOfSound** [comment]
See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2216

If you have a rudimentary understanding of Java though you might be better off implementing it yourself as a separate Java tool.  We have a PlaybackAPI so that people can read this information 👍 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md
