### ISSUE TITLE
Macbook Pro 2016 Touchbar Support

### ISSUE THREAD

**Issue by cicero19** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2411]
Love this app. It is has kept me using GPM over spotify, Google should really be supporting it. One great feature would be support for the new MBP touchbar.

**Comment by MarshallOfSound** [comment]
Will leave this open for now but unless someone can clearly define what "supporting the touchbar" actually means I will be closing this out.

I.e. I want a clear spec for what kind of interactions you expect to have with the touchbar, what buttons, what sliders, what should appear when?  Without this information I do not personally see any benefit from touch bar integration.  Please note I do have a Touch Bar MBP 2016, just don't see the benefits in this particular app 👍 

Also note this is separate from the system wide MPRemoteCommandCenter integration in this issue https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1965#issuecomment-269101328

**Comment by cicero19** [comment]
Actually, it seems the issue you linked is exactly what I was referring to. The screenshot you posted is precisely what I was thinking. If you look at the spotify app they implement this nicely. Being able to play/pause and skip tracks from any screen with the touchbar. Looks like what you posted but with skip/prev track buttons as well. Feel free to close this issue if you think it is redundant.

**Comment by Gargablegar** [comment]
The most action my touchbar gets is hot changing iterm colours. I would love to see the following functionality on my touchbar - regardless of application I am in (unsure on feasibility)
 
- Seek through track playing
- Thumb up current playing track
- Swap playlists
- Some showing of tracks in playlist

1) Playing mode, has track seek option using most of the touch bar - traditional media keys on the right of bar - Including a thumbs up button

2) Playlist button (maybe option on the right side) drops it into playlist "now playing" mode. Uses the the bar to display playlist options, swipe through your playlists to change quickly. 

3) Visualisation - total nice to have - but since its not doing anything pretty lights on the keyboard to music would be fantastic

**Comment by MarshallOfSound** [comment]
1. Is possible using the native controls I hacked into working in the linked issue above

2. Is possible but only when the application is in focus as that is how the touch bar works, (1) is an exception to the rule because their are specific global touch bar API's

3. Is not possible

**Comment by MarshallOfSound** [comment]
Got a proper module written up now for the macOS system media service

https://github.com/MarshallOfSound/electron-media-service

I'll be moving our existing windows and linux logic into there over the coming days so it's a truly cross platform module then pull it into here 👍
