### ISSUE TITLE
media keys ignored

### ISSUE THREAD

**Issue by wchristian** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#243]
I'm on a Lenovo W520, Windows 10, with a Logitech Wave 450 keyboard. On the in-chrome Google Play Music player the play/pause key works fine, but the Desktop Player ignores it, and i can't even set it in the settings.

**Comment by MarshallOfSound** [comment]
Because it works in chrome it won't work in this player (stupid right?)

Just remove the google play music extension from chrome and try again

A reboot *might* be required

**Comment by tf2manu994** [comment]
@MarshallOfSound Unrelated, but I think you should make an FAQ on the main site that answers questions like these :P also other causes for this can be having Spotify or iTunes open.

Also, the fix for me was to close spotify, then uninstall the extenstion then go to [chrome://restart](chrome://restart)

**Comment by MarshallOfSound** [comment]
FAQ incoming
