### ISSUE TITLE
cache clearing is not working as described

### ISSUE THREAD

**Issue by rdslw** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2495]
OS: Windows 10, v1703
App: 4.3.0

In settings, there is a button labeled 'REFRESH LIBRARY' which is described as "Clear local cache and refresh all song and playlist information."

Upon clicking I would expect that cache directory would be cleared. It is not the case.

**Comment by jostrander** [comment]
Can you confirm it does something in Chrome? That's a GPM setting, so more than likely it clears out some sort of local storage cache information. Nothing we can really do about this either way honestly.

**Comment by jostrander** [comment]
![image](https://cloud.githubusercontent.com/assets/760989/25774257/33080432-325a-11e7-9dca-7c2051da40e5.png)

This is more than likely what it clears out, but it will be added again on the next refresh anyway, so rather pointless other than if there is stale data there.

**Comment by rdslw** [comment]
I tried it under Chrome, but my chrome folder is around 1.3gb so hard to observe. 
Also I didnt use chrome for google play recently, so it didnt have a chance to cache much data. 

What about different approach: would you consider then adding such AppData\Roaming\Google Play Music Desktop Player\Cache" clearing to the 'Desktop Setting's ?

**Comment by eladavron** [comment]
Not working for me either.
In chrome it works fine - you can tell because when you click the "Refresh Library" button, Google Play Music reloads.
In the desktop app, it doesn't - unless I click the button like 10-20 times in a row (it eventually 'registers' and refreshes - reloading the entire interface, but it sometimes doesn't work at all and sometimes requires a lot of clicks).
