### ISSUE TITLE
The app is draining my battery, it's always in the list of apps using significant energy

### ISSUE THREAD

**Issue by raarts** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2529]
**OS:**

OSX

**Issue Descriptions:**

It's always in the list of apps using significant energy.

**Steps to Reproduce:**

It's always there.

**Comment by MarshallOfSound** [comment]
This is entirely due to this line of code, unfortunately, due to graphical glitches this line is required for now.  Each release I test to see if we can disable it but not yet 👍 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/b8c113cce72772e380b15d3bf6d88b3d92c34f55/src/main/configureApp.js#L13

**Comment by SolarLiner** [comment]
Wait, how could this target darwin when the conditional applies to all OSes *but* darwin?
