### ISSUE TITLE
Windows Sleeps During Playback

### ISSUE THREAD

**Issue by avlec** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2557]
**OS:** Windows 10

**Issue Descriptions:** During playback windows can go to sleep causing the playback to be paused until the computer is re-woken.

**Steps to Reproduce:** Idle till windows sleeps.

**Comment by MarshallOfSound** [comment]
@avlec There is an option in settings to "Stop your computer from sleeping while GPMDP is open"

**Comment by EastWanLuSt** [comment]
Hi @MarshallOfSound ,

I'd like to re-open this because I have the same issue and tried to follow your advice.  (I'm using Windows 10 Pro with GPMDP downloaed from Microsoft Store.)

The setting "Stop your computer from sleeping while GPMDP is open" does indeed prevent the computer from sleeping, but it also prevents the screen from turning off. (The German translation describes this better, because it says "Prevent *screen* from turning off while GPMDP is open".)

What I would expect from such a setting is that it prevents the system from going to sleep when audio is playing but lets it turn off the screen like normal (to save battery). 

The real problem here is that even if I set the "Sleep" option to "Never" in the power plan, the music will still turn off a few seconds after the screen turns off.

I suppose this has to do with the windows Modern Standby (https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/functional-overview-of-modern-standby). That page says that Microsoft Store apps can register as background tasks. 

Maybe this is something that you could add? Because I really think that GPMDP is a great program, but it just uses drains the battery too much if the screen is on all the time.

What is interesting: If I use Google Music in Edge (with "Sleep" to "Never"), the music will continue to play after the screen turns off. In Chrome it will not (even with audio exclusive mode enabled), just like in GPMDP.

Thanks!

**Comment by MarshallOfSound** [comment]
@EastWanLuSt This isn't something I can address. Edge is implemented in an entirely different way to Chromium and because of this they can offload media to a background thread so it works in "semi-sleep" mode.  We can't do that so the best we can do is set your computer to not sleep at all.

If you want a workaround for the battery issue, just set your brightness to 0 😆

**Comment by stevenolsen** [comment]
Could this option be enabled by default? I turned off sleep but kept the monitor turning off and it was still happening. It's quite jarring to have this occur and not realize why. This caused me to think some external app was causing the sleep (as silly as that sounds). The functionality should be similar to a video player and not put the computer to sleep while in use.

**Comment by MarshallOfSound** [comment]
@stevenolsen Not by default no, that would cause unexpected MASSIVE battery drain to a large majority of users who don't use this feature.

**Comment by stevenolsen** [comment]
@MarshallOfSound I did not consider that because I only use this on my desktop. You could always scan to see if it's a laptop or desktop and enable accordingly. A step further could be if there's a change in power, as in a laptop going from battery to AC, then enable the option but a permanent option is fine too based on the machine type.
