### ISSUE TITLE
Go to url does not work if music is playing

### ISSUE THREAD

**Issue by nmonterroso** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2582]
**OS:**
macOS Sierra 10.12.5

**Issue Descriptions:**
Using the "go to url" functionality does not work if I have music playing. #1791 is related although that looked like it was a regex update possibly to match the latest google music urls. If I stop music playback I'm able to use the feature.

Could this be because when I'm on the Google Music website in my browser and I try to leave the page as music is playing I get a `confirm` dialog, and that dialog is being suppressed in the desktop player?

**Steps to Reproduce:**
1. Open the desktop player
2. Start playing music
3. Select view -> go to url from the menu
4. Paste a valid google music url (`https://play.google.com/music/r/m/Lmfbcdi7lg4inxvv3nydqyzor4y?t=Peaceful_Stroll_` is the link from the tests)

**expected results**: the window's location updates to the URL from the modal
**actual results**: the modal closes, and my location is not updated

Alternatively, I think it'd be helpful if there was a message on the modal dialog indicating that playback needs to be stopped before we're able to use this feature.

**Comment by MarshallOfSound** [comment]
This is because GPM registers a `onbeforeunload` event handler and stops the page navigation while music is playing if it isn't a hash change.

Although that is a valid URL it results in a full page load instead of an in-page transition.  This is expected behaviour as far as GPM is concerned.  Maybe it could be a little more informative but that's just how electron handles `beforeunload` events.

See https://github.com/electron/electron/issues/2579 for more information on electrons position on this event

**Comment by bakkerthehacker** [comment]
Why is this closed?

I have the same issue and would like to be able to go to urls when I am playing music.

**Comment by jwmann** [comment]
Couldn't we force pause the Music when we press "Let's go" so we don't have to worry about it?
