### ISSUE TITLE
Can't have custom taskbar icon

### ISSUE THREAD

**Issue by ttamttamS** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2585]
**OS:**
Windows 10
**Issue Descriptions:**
When I use the change icon feature in windows for shortcuts to make the GPMDP app match the rest of the apps on my taskbar, the icon changes, when I launch it, it changes back to the default one.
**Steps to Reproduce:**
Take shortcut, right click -> properties -> change icon -> select icon
Then right click shortcut -> add to taskbar
After launching from the taskbar the icon will change back to the default GPMDP icon.
If this does not happen, exit GPMDP and try again, it seems to happen when the app isn't running in the background.

**Comment by MarshallOfSound** [comment]
@ttamttamS That's because you are changing the icon for `Update.exe` (the launch trampoline for GPMDP).  If you want to change the icon of the launched app you have to go to the containing folder for `Update.exe` and go into the app version folder (4.3.0 for instance) and change the icon for the actual GPMDP executable

**Comment by basicallyisuck** [comment]
Actually it is still an issue because those (versioned) executables don't run as the program. The target on the active application is `C:\Users\****\AppData\Local\GPMDP_3\Update.exe --processStart "Google Play Music Desktop Player.exe`

Changing the icon for (a shortcut of) the versioned executable is not effective because a separate application from the shortcut opens. 

Hopefully this will be seen and the issue will be reopened.
