### ISSUE TITLE
The songs in the computer won't show up or play when I choose this application. Is this meant to be this way ie only to play songs synced with google? By the way, I use linux mint 17.1

### ISSUE THREAD

**Issue by nobodyme** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2601]
**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Yes this isn't a player for local media. Only a wrapper around the web interface.

**Comment by nobodyme** [comment]
Okay, thanks man for taking your time

**Comment by tejaskasetty** [comment]
@jostrander But isn't it good to add this as a feature, because first of all linux based OS don't have a good operating system. And mobile app supports the feature to play local or downloaded music files.
Secondly, if there is internet connection then all we see is a blank white screen. Instead it would be better to load the layout even if we are offline but ask the user to login or connect to the net to load the content on the server.
In these cases, the user can be allowed to play local files. Won't this be a wonderful feature. This would make it the best music player in linux. Because I just love it and also the player quality.

**Comment by SolarLiner** [comment]
@tejaskasetty for your local music, [Lollypop](http://gnumdk.github.io/lollypop-web/) is *quite* good.

Playing local tracks is beyond the scope of the app, so I don't see that being implemented ever.
