### ISSUE TITLE
Disable CTRL-R reloading

### ISSUE THREAD

**Issue by pschfr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2643]
**OS:**
Ubuntu 16.04

**Issue Descriptions:**
Often I listen to music while developing websites, when I alt-tab into GPMDP by accident instead of Chrome, I'll hit ctrl-r, and I think GPMDP should ignore that and not reload.

**Steps to Reproduce:**
Hit ctrl-r

**Comment by SolarLiner** [comment]
No. Please no. I use GDPDM on my laptop and need to hit CRTL-R to reload the window on connectivity changes. This is a very useful shortcut for me, and I am sure for a lot of people.

Just because you use it "by accident" doesn't mean that nobody should be able to use it.

**Comment by MarshallOfSound** [comment]
This is very useful to a lot of people and as mentioned above, accidentally triggering a shortcut is not a use case for removing it.  Going to close this out as won't fix.

The reload shortcut is very useful for recovering GPMDP from an unknown state as it is handled in the main process instead of a potentially bugged / crashed renderer process.
