### ISSUE TITLE
Google login API not launching at startup

### ISSUE THREAD

**Issue by BCPianist** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2682]
Hey There!
The Google login API is not launching at startup

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1192783/debug_info.zip)

**OS:**
macOS 10.12.5

**Issue Descriptions:**
When the app opens, no google sign in prompt is shown.
All there is is a blank window with an orange title bar.
* Have tried uninstalling the app (with AppCleaner to prevent residual data from staying)

**Comment by MarshallOfSound** [comment]
The app clearly launched if you managed to get the debug zip file so that's a good start 👍 

All I can suggest here is disabling and proxy or VPN and trying again.  Or trying a different network.  The white screen normally just means it failed to load for some reason.  Happy to help troubleshoot in this issue thread, but closing now as it's a network / device issue.
