### ISSUE TITLE
Sound won't play after installing

### ISSUE THREAD

**Issue by Jezza-x3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2720]
**OS:** Windows 10

**Issue Descriptions:** ENTIRE computers sound doesn't function

**Steps to Reproduce:** Just install it and wait an hour.

Using Sound Blaster Z sound card to play music with and speakers. I installed it once and it happened. I thought I got a virus and ruled this out and never could guess what it was. I couldn't play sound for the next 2 days and it was extremely frustrating. I restored the pc to previous restore times and nothing.. I was baffled and still am. Then, I installed this 2 hours ago for the second time and it has happened again. I went to watch a movie with MPC-HC like always and boom, no sound. My music app clementine won't play sound. Nothing at all will play sound. My playback devices are set correctly. My sound settings are no different than they were. My drivers are updated as I checked that first when it happened the first time. That was like 5 days ago. I uninstalled it with Revo Uninstaller and deleted everything to do with it in hopes rebooting will fix it(including debug 👎). I'll get back to you on the reboot part.

**Comment by MarshallOfSound** [comment]
@Jezza-x3 This isn't something we can really help with here 😢 

Basically, it will be one of two things broken drivers or broken windows.  Because no one has reported this before (to my knowledge) I have to assume it isn't an issue with windows, so it must be an issue with your drivers.

I would recommend checking device manager and windows errors to see if you can figure out why your sound device stops functioning.  If you figure it out you should send the logs to the sound cards manufacturer and hope they fix it and issue an update.
