### ISSUE TITLE
Frame Drops in GPMDP

### ISSUE THREAD

**Issue by Cyndre** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2724]
**OS:** Windows 10H
**Issue Descriptions:** Noticeable frame drops in the player, all fixes conducted, even a reinstall. 

**Steps to Reproduce:**
This may vary by machine, and in no way would mine be unable to run the player at my monitors refresh rate, maybe ultra-wide incompatibility? Anyways, there seems to be no underlying cause outside of the player itself. Both in windows and fullscreen, noticable 'skipping' of elements occurs. There is no telltale ways to reproduce, and I have checked the GPM website and this anomaly never popped up. 
Perhaps more optimizations will need to be at play for this issue to be resolved? My system should be more than capable to drive such a workload.

**Comment by MarshallOfSound** [comment]
This issue is pretty vague and after reading through it a few times I'm not sure exactly what you're experiencing here.  A screencast of interactions might help.

But regardless of the symptoms, if your analysis is correct and it is just frames dropping it won't an issue with this player rather an issue with GPM's code (which we don't control).

Happy to help you track it down so you can report it on product forums but I doubt it's an issue on our side of things.
