### ISSUE TITLE
JSON api not correct time section

### ISSUE THREAD

**Issue by numfin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2728]
(sry for rly bad eng)
**OS:**
windows 10 last update

**Issue Descriptions:**
In json api as docs said it is possible to see current time of track. In real it shows the time we listening all tracks. 

![](https://image.prntscr.com/image/SzmolV5MTF2ztqizrDsqHQ.png)

![](https://image.prntscr.com/image/oiKBeEx9TAqr3d4YgJqKkA.png)

**Steps to Reproduce:**

just tap in the end of of track and wait when next track start. It will not start from 0 it continues to increment

**Comment by MZimmermann** [comment]
Apparently a side-effect of the fix for #2630. The Audio-element gets re-used across multiple tracks and thus the time running won't reset upon track-change (the total length of the current track will).
Could gmusic be modified to store the audio-element's running total at track-change and then subtract that number when reporting the current track progress?
E.g.:
timeAtTrackChange = 0;
First track, length 60 seconds
trackProgress = reported trackProgress - timeAtTrackChange
running total at end should be 60, so set timeAtTrackChange= 60
Second track, 120 seconds
First second would report trackProgress as 61
so calculate trackProgress again as reported trackProgress - timeAtTrackChange (61-60=1 and so on)

Would probably break if the track progress decides to reset in the middle of a song, but up until now the time seems to climb pretty much indefinitely. Seeking within a track seems to accurately subtract and add seconds to the total running time, but there's always that accumulation of all the tracks before added on top of it.
