### ISSUE TITLE
oauth support?

### ISSUE THREAD

**Issue by the1plummie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#275]
I would try this if I don't have to type my google username/password into your app :)

**Comment by FISHunderscore** [comment]
It should be perfectly safe - the desktop player is essentially just a specialized web browser. Signing in to it should be as safe as signing in in Chrome/Firefox.

**Comment by MarshallOfSound** [comment]
Basically what @FISHunderscore said :+1:

**Comment by tjkirch** [comment]
It'd be nice if users didn't have to trust you, though.  That's why systems like oAuth exist.  Not everyone can understand the source well enough to be comfortable entering their credentials.

If you're not happy with that option, an alternative is what Radiant Player for Mac does -- you can log in to Google via Safari, and since Radiant uses Safari to render the page, the cookie can be safely reused and the user doesn't have to trust another application.  I'm not familiar with Electron, but if it's based on Chromium, could we do something similar?

**Comment by MarshallOfSound** [comment]
Wait... So you're perfectly happy that an application can just steal your cookies from another application?!?!?  But logging in to a separate application securely is somehow bad?

In any case, that is not possible as chromium/chrome encrypts cookie storage.

Also, oAuth is not available for Google play music as there is no API for it.  It just isn't possible

**Comment by tjkirch** [comment]
Nothing is stolen, it's Safari using its own cookie. It's not transferred outside the Safari context.

"logging in to a separate application securely" is the part that requires trust. Unless it's a Google signed binary, or you know the code, you have to take a leap.

I understand your reaction, but please consider that there may be some bias since you wrote the application. It'd be nice to highlight security in the messaging if people are to trust their (valuable) credentials to the software.

**Comment by MarshallOfSound** [comment]
I get what you're saying, and yeah I am probably a bit biased.  But let's be real here.

* If you are worried about security as much to not trust a Open Source application that is code signed going through googles login process you probably have 2 factor authentication so you're fine
* If you don't have 2FA then you could be password sniffed through thousands of ways more discreet then a google play music desktop application.

Although you are right this code is not signed by google, my signing cert has a trust rating that comes with it.  (Windows SmartScreen automatically assigns a "trust" value) and no one has EVER reported any issues before.

Like I said, if I could use oAuth I would.  But unfortunately I just can't :cry: Blame Google for that one.

Is there anything else you can think of (excluding oAuth and using chromes cookies) that would increase the trust some users will need to use this application?

**Comment by the1plummie** [comment]
Ah you're right, there's no oauth for google music. they do have API for google play. weird that that doesn't extend into music :\

**Comment by dustintheweb** [comment]
This conversation provides great insight for the security conscious person deciding whether or not to use your app. Crafting a small blurb (in the spirit of your responses) and adding it to the readme would help increase your user base even further.

**Comment by ryanmt** [comment]
It would also be a convenience to the security minded developers to link to the code you are using for the login screen.

**Comment by jostrander** [comment]
There is literally no code for the login screen. GPM sits inside of a webview which can be thought of as an iframe.

**Comment by joaomoreno** [comment]
I was very excited to try out this app, but once I saw that login screen I noped out of it. 😢
