### ISSUE TITLE
WebSocket API Track channel double fires on song change

### ISSUE THREAD

**Issue by tjhrulz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2788]
Hello again found another issue with the websocket API.
OS:
Windows 10
Issue Descriptions:
Whenever the Websocket API is opened and you change songs the track event double fires. Seems to only happen if you next/previous and not if you let the song finish on its own. If I had to guess it may have to do with the time channel still being messed up as it does not reset unless you next/previous, but I am likely wrong in that regards.

Steps to Reproduce:
1.Open websocket connection
2.Skip to next song

**Comment by MarshallOfSound** [comment]
@tjhrulz This is expected behavior, we go with with a "fire first ask questions later" policy with the websocket events.  The first time we emit the song change notification the song hasn't loaded yet so we don't know it's length.  The second time we emit is when the song has loaded and we now know the songs duration 👍
