### ISSUE TITLE
Intermittent Last.fm scrobbling in 4.4.1

### ISSUE THREAD

**Issue by ryanbr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2805]
**OS:** 
Windows 10 x64
Player ver: 4.4.1

**Issue Descriptions:**

Unreliable last.fm scrobbling, either Maximised / or minmised (should it really matter?) Play through entire albums with nothing showing up in last.fm. 2 machines (work and home) having the same issue.

Shows I'm currently logged into last.fm via GPMDP. 

Not sure how to debug the issue.

**Comment by EricHarvey** [comment]
I think it's something to do with [this](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/0d5e22fecac7ba11f4f54e517aa02639c6511ce7/src/renderer/windows/GPMWebView/playback/handler.js#L62), the 'change:track:scrobble` event doesn't seem to be firing or it's not passing the check for playtime or something? I haven't actually tested it but as far as I can tell the _scrobbling now_ event is always sent and updates for every playing track, but the event for sending a _scrobbled_ track does not always fire

**Comment by celerno** [comment]
I confirm. Same issue is happening with one particularity on my end: last.fm page says it is actually scrobling the current song, but it never finishes to add it to my list of recently played.
At the screenshot attached you'll be able to see this behavior. 
Songs from Sep 13th where played from spotify. 
Primus song has been the only one added since I've downloaded this app.  
![image](https://user-images.githubusercontent.com/2898916/31241111-82701de4-a9c8-11e7-8d0b-bca924ba2c6d.png)

**Comment by srichter** [comment]
In #2740 Samuel mentions it has been fixed in master; we're just waiting for the next release.

**Comment by MarshallOfSound** [comment]
> In #2740 Samuel mentions it has been fixed in master; we're just waiting for the next release.

👍
