### ISSUE TITLE
Drain a lot of power running on Macbook Pro 2017 with touch bar of High Sierra system

### ISSUE THREAD

**Issue by Henry-YiW** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2808]
The Energy impact while playing music is 60-100, and the avg energy impact is 27.06, I don't know what's wrong? And the hotkey bundling is not configurable, that whatever I type won't be reflected on the hotkey blank. 

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by Jim-Zenn** [comment]
Same here. I don't even have the touchbar macbook. Just 2015 model with High Sierra. It was the same when I had Sierra.

**Comment by MarshallOfSound** [comment]
Performance and energy usage concerns have been raised before but have been found every time to be a result of GPM itself rather than GPMDP logic.  Some users have reported success with a combination of minimizing the window and staying on the home page of GPM but 🤷‍♂️ I've never really had energy issues so I can't speak to those workarounds
