### ISSUE TITLE
GPMDP doesn´t start 

### ISSUE THREAD

**Issue by dml830830** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2831]
Hey There!

Recently I updated to Windows 10 Build 17017.rs and then the app doesn´t start 
![captura](https://user-images.githubusercontent.com/32906578/31727621-a7ac192e-b3ef-11e7-946a-6f7c9cf0a6f4.JPG)

**Comment by collinjackson93** [comment]
I'm seeing something that looks similar on OS X 10.12.6 (Sierra) with version 4.4.1 of the application. I can still access the settings popup via <kbd>⌘</kbd>+<kbd>,</kbd>, but the main application window is empty. I'm not sure what spurred the issue, because I didn't update either GPMDP or my OS and the issue started yesterday for me. Maybe Google updated their endpoint?

**Comment by bradmurray** [comment]
I have the same problem on OSX 10.13 with 4.4.1. This is a fresh install as I've never had the application before. When I try to quit is has the be forced closed. I am seeing the following error in my log: "LSExceptions shared instance invalidated for timeout."

**Comment by jostrander** [comment]
Usually the white screen of death is due to either an overzealous firewall or GPU issue.

**Comment by MarshallOfSound** [comment]
> Usually the white screen of death is due to either an overzealous firewall or GPU issue.

👍 👍 👍 👍 

Nothing has changed in the app in a looong time, this will be a firewall change on users side of things 👍
