### ISSUE TITLE
Feature request: skip/disable "Instrumental" Tracks

### ISSUE THREAD

**Issue by Tune389** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2848]
Hi, thanks for that awesome player. 

I have a little feature request. Should be easy to build (like the "skip disliked songs"). Just another checkbox, to skip all tracks which ends with "(Instrumental)".

**Comment by MarshallOfSound** [comment]
> Should be easy to build

It's not easy to build, in fact it's basically not possible from our side of things.  We can skip disliked songs because there is something in the UI for each song with no user interaction that shows whether it's liked or not.  Genre's are behind several fetch requests and user interactions.

Would ask Google for this on their product forums

**Comment by Tune389** [comment]
Thats not a specific "Genre". I'm talking about the Track title, "(Instrumental)" is a part of it. Track titles should be available without additional requests.
![grafik](https://user-images.githubusercontent.com/4512259/32103916-ac5cd0d2-bb22-11e7-9890-f5ebedefffa4.png)
