### ISSUE TITLE
New Feature: Add Twitter #NowPlaying Support

### ISSUE THREAD

**Issue by angiest** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2893]
Google offers the manual ability to share individual tracks but doesn't have the ability to "stream" currently playing track information to social media (such as Twitter's #NowPlaying" hashtag), a feature Spotify has.

It _seems_ like it should be possible to add integration at least for Twitter to support for this.  Perhaps Something along the lines of "NowPlaying <track title> by <artist> on Google Play Music <track URL>.  A bonus would be to add additional information to the tweet, such as custom hashtags.

*** Note ***

I have last.fm support enabled and I looked there for similar functionality.  Unfortunately, it appears to require enabling an RSS feed and then using IFTTT to perform this task.  Not exactly clean.

**Comment by jostrander** [comment]
This may be something for the future plugins system but I don't think this would be added unless someone were to implement and PR this.

**Comment by jostrander** [comment]
I don't believe this is something we can implement. It would require handling oauth credentials inside of the application, which is quite unsafe. With spotify this works because they can keep the oauth credentials safely on their server, and identify users by their spotify account. I'm going to close this out as a wontfix as it would require extensive time and security investment. However if someone can see a better way we may look into it.
