### ISSUE TITLE
Add adblocking functionality to GMPDP

### ISSUE THREAD

**Issue by andromedastudios1** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2941]
Hi, 
Request for feature exactly as above (don't know how to add enhancement tag), to stop the ads for free users when starting a radio or that pop up once in a while. 
Don't exactly know enough JS to be dangerous, but I am willing to take a crack at it. 

Thanks.

**Comment by jostrander** [comment]
I believe this is something we've decided previously against implementing in the app. Trying to stay as far out of the grey area as possible. You can implement ad blocking at the network level or by using adblocking dns as an alternative solution.

**Comment by tabedzki** [comment]
Hi @jostrander,
I did a quick search for ad blocking software in the issues and I couldn't find a reason against the implementation elsewhere aside from API differences. Is there a way to build a feature that would allow the end user to integrate the ad-blocker (such as u-origin) after you guys provided the software so that way you guys can stay out of that gray zone?
Thanks in advance.

**Comment by CHEF-KOCH** [comment]
Ad-blocking is not illegal nor against any laws or terms. The web version does not even check if an ad-blocker like uBO is installed or not.
