### ISSUE TITLE
Last.Fm scrobbling not working

### ISSUE THREAD

**Issue by stvnjohnson** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2973]
OS: Windows 10 Pro

Just updated to the latest version of the desktop player, and my last.fm scrobbling is broken.  Last.fm can see what i am currently playing but never pushes those songs into the scrobbled list.  In the previous version, this was happening only while playing a song that I had imported into the library, but now it occurs on all songs, imported or streamed from the google play library.

Additionally (and perhaps related), the song progress bar only updates when the window is in focus.  If I minimize the app window, it will not update with the songs progress but remain frozen where it was when the window was minimized.

Edit/Update:
Scrobbling works for some albums streamed from the library, but not all.  For example, "Man in the Box" scrobbled from Alice in Chain's "Facelift", but "Limo Wreck" would not scrobble from Soundgarden's "Superunknown".  Neither of those albums was imported, so i'm not sure why one will scrobble but the other will not.  I've tried several songs from imported albums, and none of those will scrobble.

**Comment by Razgriz375** [comment]
Having the same issue with ListenBrainz. Entered my API key, can see it sending now playing information, but that's it, doesn't actually add the song as listened. So both Last.FM and ListenBrainz are doing the same thing for me.

**Comment by hohy** [comment]
I have problems with Last.fm scrobbling too. It works fine for couple days, but then it randomly stops and I can only see now playing info but it's not recorded when a song ends. When I restart the player, it works fine for some time again.

**Comment by blakkheimgw** [comment]
I'm experiencing the same issue. I was waiting for the 4.5.0 version because it was supposed to fix this issue (see [#2740](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2740))

Regards.

**Comment by claudiutms** [comment]
I am having the same issue with the latest 4.5.0 build.
On the previous build 4.3.0 worked just fine for me.

**Comment by Mynny** [comment]
still the same issue with 4.5.0 for me, switching back to web player :(

**Comment by Maddieman** [comment]
Works ok for me (so far) as long as I keep the mini player open.  If I minimise or hide the player, it stops scrobbling (windows 7).

**Comment by maetthu** [comment]
For me (on Linux), it doesn't seem to matter whether I have the player window open or not (mini player or main window), no matter if it's a fresh (re)start or the player was running and toggling the windows. I can't really reproduce what causes it to stop scrobbling,, sometimes it works, sometimes it doesn't.

**Comment by adityaprasoon** [comment]
I have exactly the same problem, OS - Windows 10

**Comment by claudiutms** [comment]
@Maddieman thanks for the suggestion. As long as I keep the app either maximized or in mini mode, the scrobbling seems to be working, though it's a very strange workaround. I'd have no idea what causes it to scrobble if it is maximized or in mini player. 

I am running on Windows 10 17074 Insider Build.

**Comment by alexszf** [comment]
Scrobbling is also broken for me, Win10 & running latest version. It does seem to reasonably consistently scrobble the first and last tracks of my queue though.

**Comment by tjohns0n** [comment]
Getting random scrobbles dropped, usually near the end of an album. Using the mini player seems to work for now.

**Comment by StanleyRussian** [comment]
Same here. Everything was fine with previous version. Maximising player seems to work

**Comment by rfuhrer** [comment]
Similar issue here.  I noticed that before the latest version I had to go in and clean up some duplicate scrobbles (eg. a 10 minute track would be scrobbled 4 times with 2 minutes between each scrobble), but now I don't have that issue since I can go 7 hours with only 2 scrobbles actually counting lol.

I almost always have my player minimized since I'm at work so I believe that's related to the issue. It seems my scrobbles from home are making it through and i always have it on the foreground of my 2nd monitor while I'm playing games.

Just did a quick test here.  I minimized the player and let a song play all the way through.  While it was playing Last.fm said I was scrobbling the song currently.  Once the song finished, the next song started and it updated saying the new song was currently scrobbling.  The finished song was no where to be seen in my history.
I then maximized the player part way through this second song.  It then added a scrobble for this track (even though it wasn't done, so i temporarily had 2 copies in my history, one scrobbled a couple minutes ago and one "currently scrobbling" version).  Once the song finished that scrobble stayed and it moved on to the next song.

Based only on this test and not actually looking at the code, it seems like there's 2 events:
1. Currently scrobbling -  Happens when the track changes and never seems to fail
2. Record scrobble - Probably happens when some percentage of the song is done so you don't get a scrobble for a song you listened to for 5 seconds and hit skip

Seems like the 2nd event isn't firing if the window isn't "active".  That's my best guess anyways

**Comment by ChristianWilkie** [comment]
same issue here, mini player sorta works at least

**Comment by MarshallOfSound** [comment]
Root cause is #3018

**Comment by Landen13** [comment]
Scrobbling still doesn't work when player is minimized. v4.5.0. Please, reopen.
