### ISSUE TITLE
Mini Player Issue Windows platform

### ISSUE THREAD

**Issue by obscurbia** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3017]
Issue: When Switching to the mini player it grows in size and never seems to stop unless I exit. Upon exiting  the desktop player is zoomed in about 400%.
OS: Windows 10
Replication:
Step 1: Open the mini player 
Step 2: Watch it fill the screen while hogging a about 25% of my i76600k's power
Version: 4.5.0

**Comment by nickp10** [comment]
I can reproduce this as well. It only happens when I move the mini player around the desktop. Each time I move the mini player, it grows by about 5px. Here is a screen recording of the issue showing how to reproduce it:

https://drive.google.com/open?id=1N9eb-c98Fiar0zmajYOVaU21kKc2vthK

**Comment by silvernode** [comment]
In order to help find out if this is a platform specific bug or just the application in general, I tried it out on my Linux box but could not reproduce the steps listed above.  Additionally, activating and deactivating mini player rapidly worked flawlessly. So it seems as though the bug is related to the Windows client and not the core application.

**OS:** KDE Neon LTS 
**Desktop Version:** 5.12.2  
**GPMDP Version:** 4.5.0

**Comment by MarshallOfSound** [comment]
Merging into #2269
