### ISSUE TITLE
[SUGGESTION] Bring player to front when you attempt to open another instance

### ISSUE THREAD

**Issue by ryanfoleysfc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3053]
**OS:**
Windows 10 x64
**GPMDP Version:**
1.4.4.0
**Issue Descriptions:**
I'm using a keyboard hotkey to open this app and it would be nice if the program would open up again when I press the hotkey while it's already running in the background - right now it looks like it attempts to open another instance of GPMDP and immediately closes it whenever it realizes another instance is open.

**Comment by MarshallOfSound** [comment]
> Bring player to front when you attempt to open another instance

We already do this, see [this code](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/60649402bd2ee91e3766c31530df3e0051e9f2b5/src/index.js#L33)

Notice how we try to restore / show the window when another instance is launched.  If it isn't happening on your machine it's because either

* (a) Windows is blocking it as your hotkey doesn't trigger the launch as a foreground process
* (b) Your hotkey is launching the wrong executable
