### ISSUE TITLE
Make Tray Icon / AppIndicator Icon optional

### ISSUE THREAD

**Issue by mpdeimos** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3158]
**OS:** Arch Linux / FlatPak Installation

**GPMDP Version:** 4.5.0

**Issue Descriptions:** I'd like to keep my appindicator tray as clean as possible and GPMDP provides no way to hide the appindicator/tray icon. The need for a tray icon is quite low (at least for me), as the player can be controlled via MPRIS_v2.

**Steps to Reproduce:** Start GPMDP, AppIndicator is visible.

**Comment by MarshallOfSound** [comment]
This has been discussed countless times, it will be declined every time, there is too much coupling between window behavior / app control and the tray icon

**Comment by mpdeimos** [comment]
Searched for "appindicator"; should have tried "tray" instead. My bad. Sorry.

Actually I followed some of the discussions you had in that threads right now. I still cannot agree :(

As one of the former Winamp devs I know what it means to maintain a *very* customizable app. Indeed, we had a show tray icon/hide to tray functionality there as well. Clearly, Winamp was just for Windows, so it's more easy to test all the edge cases, but we managed it.
However, simply stating that "coupling" is too high makes me sad as tray icons are a relict of 1st generation desktop environments. You kind of experience this by the "countless" discussions/issues regarding this topic here.

You mention in the comments that you do not want to have the Window disappearing, that's the reason for the tray icon. Well, if you take a vanilla Gnome Shell installation (one that you get e.g. on Fedora or countless other Linux Distros), there is no built-in support for appindicators or tray icons. With the default settings of GPMDP the app is gone after clicking close but music continues to play. There is no immediate UI element to get it back. I haven't searched whether you received a bug report for this. Gnome handles this (maybe weird) app behavior thankfully in a good manner, as it simply unminimizes the app if you want to open it again.

...which brings me back to Winamp: This was the exact behavior if you insist to enable hide to tray but also hide the tray icon. You simply re-open the app, it detects that it's already running and brings up the running instance. This is also matches the mental model of a user: if he accidentally loses the app window, he tries to open the app again.

In fact, I've appreciated your great work with GPMDP the last years and apparently the indicator icon was just broken for me till now. In the end it's up to you to either accept a patch or provide the feature on your own. It just leaves a bad taste being enforced to an indicator icon due to customization degrees on other non-standard window behavior.

**Comment by jostrander** [comment]
I'm just going to chime in real quick to say that I'm sort of indifferent as it doesn't matter to me either way. However since this has been a recurring theme, and people have successfully created patches to remove the tray icon, I don't see why the coupling would be too much of a reason to make it a non-starter. I understand the implications as I've been in the code, but I think that it's definitely doable. personally don't want to implement this patch as it is a large scope of work to test on 3 platforms, and multiple OS', but I wouldn't be opposed to the community fixing this issue. Ultimately it's up to @MarshallOfSound as it's his project.

**Comment by SolarLiner** [comment]
First of all, thanks @mpdeimos for enabling the soundtrack that introduced my to computers and programming back in Windows XP, it was the shit :+1: 

On both Windows and Linux I have yet to use the tray icon for anything other than killing the process. Especially with media controls and MPRIS on Linux there really is no point in keeping it. Adding a toggle to disable it (and keep it enabled by default) would hurt no one and make everyone happy.
The only downside of that would be adding one more switch to the settings page, which is already quite full of nameless boxes. I might, as an inexperienced designed (heh), try to come up with an alternative design for that (especially since I need to procrastinate from my other personal projects...).
