### ISSUE TITLE
Add option to disable Youtube Music dropdown in menu bar.

### ISSUE THREAD

**Issue by darkevilmac** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3165]
Just updated to the latest version (4.6.0) and now I have a button for Youtube Music in the dropdown for GMPDL. Personally I don't plan on using Youtube Music so having an option to turn that button off would be great.

Here's an image that shows the dropdown options that were added.

![](https://i.imgur.com/LwgMq0X.png)

**Comment by MarshallOfSound** [comment]
You want an option, to disable an option, that you don't plan to use? 🤔 

Let's not 😄

**Comment by darkevilmac** [comment]
I'd like to be able to hide a button in a dropdown because I use the dropdown a lot? Just looking for an option to flat out disable the Youtube Music stuff really. Seems like it would be better suited to it's own program.

**Comment by MarshallOfSound** [comment]
@darkevilmac YouTube Music will eventually supersede Google Play Music and like 80% of the logic is re-used across the two services inside this app, that's why it was so easy to add support.  I'm not a fan of adding new options let alone adding options with the express purpose of disabling other options 🤔
