### ISSUE TITLE
Progress indicator and hover actions on taskbar icon missing on Windows 10

### ISSUE THREAD

**Issue by csicky** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3179]
I don't fill anything required, and yes there is a similar issue already. However my problem is different. I clicked the let's go button on the update prompt and now I wish I didn't. 

- I want the old icon back. (I probably can change this myself from Windows).
- I want the progress indicator back. 
- I want the previous, pause/play, next buttons back on the hover of the icon back because I use to hover on the taskbar icon and click next or pause, now I can't do that anymore
![image](https://user-images.githubusercontent.com/3931907/41839598-51327eb6-786c-11e8-94f8-69698259b061.png)

Where can I find a download link for previous version?

**Comment by rsimenok** [comment]
@csicky in [releases](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.5.0) I think :)

**Comment by csicky** [comment]
@rsimenok Thank you, found it.

Installed previous version, all good for me, but the above mentioned issues should be fixed anyway in my opinion.

**Comment by MarshallOfSound** [comment]
If there are bugs, raise them as such.  Coming into the issue tracker saying "I want" this and "I want" that is just going to get your issue closed.

There are already issues opened for the bugs you mentioned and the icon is **not** changing back.

**Comment by csicky** [comment]
Pushing a broken update will obviously make your users unhappy, of course a bug report from such users will not have that friendly tone. I use this app, it is great on version 4.5.0, I will stick to it until it works. What is still missing is a checkbox in settings to not prompt for update. I understand it is open source, but from the moment you have real users it's not just a project where you can play around with it and break it. You should have different release channels to play with it. Real users mean responsibility.

**Comment by MarshallOfSound** [comment]
You seem to be under the impression that you using open source software entitles you to some kind of support or something.  I give this out for free, along with my own time.  Just because some people happen to use it does not change it's status, no one pays me for this software, I owe no one anything.  If you think otherwise you fundamentally don't understand how open source works.

Your tone is not appreciated and definitely unnecessary.  I sincerely hope that if you continue to have discussions on this repo or on other projects you treat the maintainers with the kindness they deserve, they owe you nothing and help you and provide software for free normally in their own time.

I personally have a full time job and maintain a decent number of open source projects (this isn't even the most popular one).

If you have legitimate issues that haven't already been raised please raise new bug reports and follow the template, someone / I might get to look at them.

**Comment by csicky** [comment]
@MarshallOfSound 
Yes you are right, but still, I welcomed your app into my daily life. It was a bad feeling that essential features were missing. Sorry for hurting your feelings with my tone. It was just that the update hurt mine first :) 
This is my last comment on this issue, please forget it and don't be upset by it.
