### ISSUE TITLE
Back button is missing. Again

### ISSUE THREAD

**Issue by alexschneiderru** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3196]
Hi,
after the latest update I found back button missing from search field: https://c2n.me/3V5AeoH.png
It is one of the most important navigation elements in the app IMHO so...
Please fix it.

**Comment by EpicWolverine** [comment]
I have the same issue. I can't go back with Backspace nor with the Forward/Backward buttons on my mouse either.

**Comment by MarshallOfSound** [comment]
Deleting the issue template and not following it ain't cool 😄 

This is beyond a duplicate issues, the last like 8 issue are literally this one... 

Fixed in master

**Comment by dumrauf** [comment]
@MarshallOfSound, you've got a good bug reporting template as the

>**YOU SHOULD CHECK CLOSED ISSUES ASWELL**

saved me from opening yet another duplicate issue.

You said the bug is fixed in master - that's good to hear. When are you planning the next release? Not being able to navigate isn't the best thing in the world!

Other than that - amazing app. Keep up the great work!

**Comment by jimmyodonnell** [comment]
@MarshallOfSound @jostrander These might make your life easier:

1) Leave one of the back button issues open so that it is returned in GitHub's default search parameters.

2) Paste this somewhere:

"Missing the back button in the search bar? This bug was accidentally introduced in v4.6.0. Until the fix is released, you can always install the previous version from here: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/tag/v4.5.0"
