### ISSUE TITLE
YouTube Muisc volume is too loud 

### ISSUE THREAD

**Issue by xevrem** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3246]
**OS:** MacOS, Windows, Linux

**GPMDP Version:** 4.6.0

**Issue Descriptions:** All audio volume with YTM is too loud. The slider appears to only bring volume down to ~50% before it mutes completely (verified via pavucontrol on linux) i.e., 1% on volume slider is actually ~50% application volume when it should be 1% application volume.

**Steps to Reproduce:** play any song in YTM. All songs are only mildly reduced in volume when slider is close to mute.

**Comment by TheLimeGlass** [comment]
Can't reproduce on Windows 10.

**Comment by MarshallOfSound** [comment]
The slider and volume control is all done by YTM not by us

**Comment by BlacRyu** [comment]
> The slider and volume control is all done by YTM not by us

Does this mean that manipulating the slider in GPMDP isn't possible? I believe the real issue here is that YTM is using a linear volume slider, when it should be exponential due to how human ears perceive volume. See here for a robust explanation on that topic: https://www.dr-lex.be/info-stuff/volumecontrols.html

GPM had proper volume control with perceivable differences at each step on the slider, but YTM (as well as YouTube itself) does not. As the OP mentioned, you only really notice the differences in volume when you get the slider almost all the way to the left. I'm going to appeal to YTM to see if this can be changed, but it seems unlikely as YTM is intrinsically tied to YouTube and they can't change YouTube's slider at this point without breaking everything that relies on it. Would be nice if we could at least have an option for an exponential slider wrapped/mapped over the existing YouTube one in GPMDP.
