### ISSUE TITLE
[Suggestion] Music fade in and out on pause/unpause.

### ISSUE THREAD

**Issue by LazarLazarov** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3299]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there

I've read the other issues and I saw that the suggestion was closed because it would be complicated to hold the pause action while the music fades in. However I am suggesting to fade out the volume on pause, so save the current volume value and over 1 second fade the volume to 0. Then on unpause it would still be at 0, but then it can fade in to the saved volume value from before. The time it takes to fade in and out can be tweaked. This way you are not affecting the playing/pausing, but can still achieve the same effect. 

**OS:Windows 10**

**GPMDP Version: 4.6.1**

**Comment by MarshallOfSound** [comment]
What you describe is what was proposed in other issues and declined due to having to manage the pause logic.  In order to fade out on pause, you have to reject the pause and then pause later once you've faded out.  There are so many edge and race conditions to asyncronously pausing / playing music.  I don't want to go anywhere near that
