### ISSUE TITLE
GPMDP Fully Frozen

### ISSUE THREAD

**Issue by Jonasori** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3313]
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** MacOS 10.13.5

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Google Play Music interface is fully frozen; no clicks anywhere on the screen will do anything. Youtube Music player works great. The app itself opens great, it's just that the interface does not respond to inputs.

**Steps to Reproduce:** Open GPMDP app, try to do anything.

**Comment by charlwillia6** [comment]
I also have the same issue on Windows 7 and Manjaro 2018.08.06 with version 4.6.1 if I choose a custom theme.  I don't have as many issues if I used the default GP theme.  Other wise I have issues when I select artist pages, music stops playing, and everything loads very slow.

**Comment by cprn** [comment]
Have the same on Manjaro 18.0.3 and MacOS (girlfriend's Macbook, no idea what version). GPMDP version: 4.6.1-1 (build date 2018-07-17). It does react after a few minutes, though, when I wait after a click, and the delay seems to get longer with time, impossible to use 30 minutes after running the process. It also hogs the CPU time since the very first second it starts but doesn't seem to leak memory (at least not visibly). Keybindings seem to react with steady 5-10 second delay when the window isn't rendered (i.e. until it freezes completely).

Any workaround other than restart every 30 minutes?

**Comment by MarshallOfSound** [comment]
This was a known issue on master and will be fixed in the next release
