### ISSUE TITLE
Cannot Sign in with Security Keys

### ISSUE THREAD

**Issue by MrCaptPlanet** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3343]
**OS:**

OSX 10.13.5

**GPMDP Version:**

4.6.1

**Issue Descriptions:**

Cannot sign in with security keys into GPMDP. The security key works with signing into google chrome, and can successfully sign into the GPM website. It seems that the app does not recognize the security key and verification

**Steps to Reproduce:**

Setup a google account with USB security keys. Try to sign into google account on GPMDP. When it prompts for the security key, plug in the key and hit the button. Nothing will happen

**Comment by MarshallOfSound** [comment]
This is known / expected.  Electron does not currently support physical 2FA keys

**Comment by larsen161** [comment]
> This is known / expected. Electron does not currently support physical 2FA keys

I don't believe this is true any longer. Google Chat which is built around Electron support keys / sso now. Please consider opening this ticket and prioritising a security enhancement.
https://gsuiteupdates.googleblog.com/2018/10/securely-log-in-to-hangouts-chat.html

**Comment by jostrander** [comment]
Can you point to somewhere in electron where this is implemented?

**Comment by larsen161** [comment]
Perhaps this can shed some light onto how it's implemented.
https://drive.google.com/open?id=1Gpkp96zJU1m-3pGt0QQII8GUwkyuTjJ6

**Comment by jostrander** [comment]
So they aren't actually using electron for MFA. They are using SSO in their desktop app to open chrome and  auth to then send credentials back to the desktop. I believe this is all oauth2 flow for auth. I don't believe we can get access to this level of implementation because we don't have API access to Google play music, etc.

**Comment by pconwell** [comment]
I'm not really smart enough to know how closely this is related, but here is a currently closed issue being discussed by the electron team: https://github.com/electron/electron/issues/3226

If I am understanding it correctly, basically no one really knows but electron MIGHT support U2F natively once electron is updated to chromium 68.

**Comment by thor** [comment]
@MarshallOfSound Could this be re-opened, with a proposed feature of updating Electron from 3 to 4? (Which surely isn't going to be very particularly easy first.)

As far as I can tell, built-in support for physical security keys is present in Electron 4 and above. In that spirit, I would like to request an update from Electron 3 to Electron 4 for GPMDP. My primary motivation is the fact that I have not been able to use GPMDP since I enabled [Google's Advanced Protection Program](https://landing.google.com/advancedprotection/). 

Relevant issue being https://github.com/electron/electron/issues/15404.

**Comment by thor** [comment]
Gently bump in your direction, @MarshallOfSound. ❤️

**Comment by flyingmongoose** [comment]
Well, I've run into this myself now. Looks like I'm back to a web player for now.
