### ISSUE TITLE
:astFM: "You appear to have left the authorization process, if this is a mistake, please try again"

### ISSUE THREAD

**Issue by YamiFrankc** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3486]
Hi,

I know there are other similar issues to this, but they are months or years old. Last fm integration is a pretty cool feature that id like to have

**OS:** Windows 10

**GPMDP Version:** v 4.6.1

**Issue Descriptions:** "You appear to have left the authorization process, if this is a mistake, please try again" when trying to log in to last.fm

**Steps to Reproduce:** RIght after installing, go to the last.fm settings and try to log in

**Comment by prashantk100** [comment]
I have also encountered exact same issue..if possible provide the fix

**Comment by prashantk100** [comment]
issue partially resolved by removing all unncessary entries in C:\Windows\System32\drivers\etc\hosts file which is earlier used to block spotiy ads and now it is authorizing correctly but now it is scrobbling for the songs which I hit like/thumps up button . otherwise it is not entered in library https://www.last.fm/user/lastfmUSERID/library even when the option "Automatically love tracks that are thumped up" is unselected.
and it work perfectly from chrome web scrobbler

**Comment by MarshallOfSound** [comment]
This sounds like a HOSTS file issue or some kind of proxy / ad blocker getting in the way.  I'd suggest trying on a clean system
