### ISSUE TITLE
[Interface fix] Make tray icon play status inline with main player

### ISSUE THREAD

**Issue by rdnl** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3543]
**OS:** Windows 10 1809 64 bit

**GPMDP Version:** 4.6.1

**Issue Descriptions:**
Tray icon has inverted status from main player
When music is playing main player shows "**I I**" button and tray icon "**|>**"
Screenshot for better illustration: https://i.imgur.com/Tv8H8tD.png

(It took me 6 months to realize what's wrong and why i irritated)
**Steps to Reproduce:**
It's normal behavior for app right now

**Comment by MarshallOfSound** [comment]
This IMO is expected UX, happy to have a discussion about it below.

Basically that play/pause button in the UI indicates the action that will occur should you click that button.  I.e. It is indicating the **action** rather than **state**.

The tray icon is designed to indicate at a glance the current **state** of the player.  Therefore when it's playing the "play" logo is shown.

This is just IMO though so happy to have a discussion below

**Comment by BananaLoaf** [comment]
I strongly disagree, it would be nice to at least have an option to choose, what is displayed in the tray

**Comment by jostrander** [comment]
I disagree, the current UI is exactly what most people would expect it to be, it's very similar to the old iPhone status bar playing status:
![image](https://user-images.githubusercontent.com/760989/56584164-371c7100-65a9-11e9-81b3-4c450194eb32.png)

The icon isn't a button that causes state to change, therefore it is expected that the current state be shown, not the action in which will happen if clicked.

**Comment by BananaLoaf** [comment]
> I disagree, the current UI is exactly what most people would expect it to be, it's very similar to the old iPhone status bar playing status
This makes sense, but checkbox for that kind of thing would be nice, IMO that would eliminate some complaints from people like me and OP
