### ISSUE TITLE
Suggestion about RPC

### ISSUE THREAD

**Issue by Leozn17** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3577]
Suggestion: can put the image of artist instead google play image
Suggestion2: can change the discord rpc "game" name to Youtube Music instead google play music when using ytmusic
Suggestion3: if the first suggestion not "the best", can only put yt icon when using ytmusic

Bug:
![image](https://user-images.githubusercontent.com/51327712/58806934-8c5a9200-85ed-11e9-9d8f-0de088b3f2dc.png)
sometimes using Youtube Music, you can see "Unknown Artist"

Big thank you for the attention.

**Comment by jostrander** [comment]
To answer your suggestions:

1 is not possible, due to the way the integration works. The image presented has to be uploaded to discord ahead of time and referenced by name, making that impossible.
2. Possible, but I believe it was discussed the player name is the reason that is displayed, and until they shut down GPM that's the way @MarshallOfSound intended to keep it. 
3. Same as above, the icon is the player icon, even though it resembles the GPM icon. 

As for unknown artist, I believe that's an issue with the underlying implementation.
