### ISSUE TITLE
Song Info does not update on YouTube Music mode

### ISSUE THREAD

**Issue by mcao** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3644]
**OS:** Windows 10 x64

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Windows 10 Media Service and Discord Rich Presence song information don't change when I change songs on YouTube Music mode

**Steps to Reproduce:**
- Change to YouTube Music mode
- Play a song on YouTube Music
- Check status of Discord Rich Presence and Windows 10 media displays

**Comment by jms1989** [comment]
Same thing on linux. the window title stays on the first song as the playlist plays. :/

**Comment by wuppious** [comment]
I was bothered by this as well and decided to dive in. I'm on Linux, so the issue is probably a bit different, however these flaws should carry over to Windows as well.

It seems that the whole YouTube side of things is pretty broken in the underlying `ytmusic.js` library.

## Track failing to update
It really boils down to a single line of code: https://github.com/gmusic-utils/ytmusic.js/blob/d05c737765cf1162cfb69e983601f37f6d64a232/src/namespaces/PlaybackNamespace.js#L61
```js
      album: playerBar.__data.playerPageWatchMetadata_.albumName.runs[0].text || 'Unknown Album',
```
For YouTube videos, there might not be an `albumName`  field at all. This raises an exception caught on [the proxy trap listening on track changes ](https://github.com/gmusic-utils/ytmusic.js/blob/d05c737765cf1162cfb69e983601f37f6d64a232/src/namespaces/PlaybackNamespace.js#L224-L240) and so the track never gets updated. A simple solution is to write a guard to check that the field exists.


## Current playback time
Another issue that I noticed and debugged was that the track position did not get updated. Once again a simple problem:
https://github.com/gmusic-utils/ytmusic.js/blob/d05c737765cf1162cfb69e983601f37f6d64a232/src/namespaces/PlaybackNamespace.js#L164-L169
```js
    this._progressEl.addEventListener('value-changed', () => {
      this.emit('change:playback-time', {
        current: this.getCurrentTime(),
        total: this.getTotalTime(),
      });
    });
```
This event fires only when the progress bar is actually clicked, so GPMDP only receives current time on user interaction. A proxy solution like in the track change listener could be used here, but I'm not sure where to attach that.

**Comment by jostrander** [comment]
This should be fixed pending merge of 6.2.1 in ytmusic.js.

**Comment by mcao** [comment]
@MarshallOfSound kindly request a new release sometime soon to fix this on the stable release :)

**Comment by mcao** [comment]
For people who want fix right away: https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/branch/master/artifacts
