### ISSUE TITLE
Equalizer missing on OSX?

### ISSUE THREAD

**Issue by Nxt3** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#419]
**OS:** OSX (10.11.3)

**Issue Descriptions:** No equalizer settings.

It says there are settings for an equalizer--but they are nowhere to be found.

**Comment by MarshallOfSound** [comment]
It's currently disabled pending a bugfix in electron

**Comment by isaachess** [comment]
Any progress on this? It's been six months, still no equalizer on Mac? I probably have to stop using this product until there is an equalizer on it.

**Comment by garretttaco** [comment]
@MarshallOfSound Any update on this? Are you able to reference the bugfix in Electron?

**Comment by Roundaround** [comment]
Not entirely sure why this is closed if the bug still exists and the equalizer is still missing. Could you provide a link to the associated bug in Electron? Maybe some of your users here could help contribute if it means getting this back in!

**Comment by MarshallOfSound** [comment]
@Roundaround The bug is all the way upstream in Chromium and goes further than that to the actual spec for AudioContext not being final yet.  The underlying issue is that we can't `setSinkid` on an `AudioContext` as the spec for how that will work is not final and has not been implemented in Chromium.

As such we either have the output selector working (which requires `AudioElement.setSinkId` or the equalizer `AudioContext.connect()`.  Unfortunately the spec does say that `setSinkid` won't work on an element that has an associated AudioContext.  So we only have one or the other.  The spec for `AudioContext` holds this information.

**Comment by Roundaround** [comment]
Ah okay, thanks for the explanation. Would be nice to keep the issue open regardless though just to keep it on the radar. If nothing else, the equalizer functionality should probably be removed from the features slideshow on the website, right?

**Comment by dragonfax** [comment]
9 months later...

**Comment by Lumpenstein** [comment]
Does anybody got eqMac2 working with GPMDP ? I suppose it is the same bug that causes both are not working together.
