### ISSUE TITLE
Feature Request: Ability to choose output device

### ISSUE THREAD

**Issue by sbozzie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#47]
It'd be cool to be able to pick an output device from enabled devices on the pc.

eg: Default device is a USB headset, but I like to have music playing though speakers.

**Comment by MarshallOfSound** [comment]
Not exactly sure how this would be implemented as CefSharp handles the audio out not technically my code, but I'll look into what I need to override :smile_cat:

**Comment by MarshallOfSound** [comment]
Research into this puts it at hard -> impossible level.  Somehow we have to force windows to move a different program (the CefBrowserSubprocess) to move to a different audio device.  It looks like there might be a way to do it with undocumented Win32 calls but it's going to take a lot more research before I know if this is even possible.

Because of that I'm removing this from the 2.0 milestone and adding it to the research one

**Comment by MarshallOfSound** [comment]
Due to the way CefSharp works this has been determined as impossible without recompiling and changing CefSharp

**Comment by Servuslol** [comment]
Would it be possible at all to re-open this as an "ideal feature" in case it becomes possible in the future?

**Comment by MarshallOfSound** [comment]
@Servuslol I personally don't like the idea of issues marked as "open" that can't actually be resolved, I guess I could reopen and mark as upstream requirement but I don't really see the point.  I'm about to write up a massive ticket for the `3.0.0` milestone so I'll try mention this in there

**Comment by Servuslol** [comment]
Thanks man, appreciate it! It would make recording games/streaming with
music on a lot more possible.

**Comment by MarshallOfSound** [comment]
Just to keep you up to date though, in the `3.0.0` milestone I can make use of this API

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

To change audio device.  The only problem is how completely unstable that API is.... :+1: 

I'll see how it goes though
