### ISSUE TITLE
How to tell what version I have installed

### ISSUE THREAD

**Issue by cnanney** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#498]
**OS:**
Windows 7 x64

**Issue Descriptions:**
Maybe I'm dense, but can't see what version of the app I have installed. It auto-updated earlier, but I didn't make note of the new version number, and there is no "about" screen that gives me that info, and I can't find it in settings either. When I report a bug I'd like to be able to include the version, or does it not matter as it is assumed everyone will always be auto-updated to latest?

**Comment by MarshallOfSound** [comment]
Basically I will assume you are on latest.  Because the way to auto updater works is when an update is released it will ask you to install it.  Even if you say "Not Now" next time you relaunch the app the update will be installed.  (You won't even notice)

That's partly why the squirrel updater is so awesome, I don't have to rely on users to keep the app up to date.  If you really want to figure out the version though, you can see in Control Panel.  Or in the properties of the actual executable

**Comment by MightyPork** [comment]
@MarshallOfSound Should we have this info in the tray menu? Think it could be handy. Actually more stuff from the (now removed) menubar could put be there.

**Comment by MarshallOfSound** [comment]
What menubar was removed?

And I don't want to clog up that right click menu any more, it's already massive on windows :)

**Comment by MightyPork** [comment]
when you first added the native frames, there was a menubar on Linux, now there isn't. So practically no way to get to the help menu etc.

How about adding those items only outside windows or something?

**Comment by MarshallOfSound** [comment]
@MightyPork They aren't removed, they are simply hidden.  They are all accessible via keyboard shortcuts and the menu can be brought up by hitting "alt" I belive

**Comment by MightyPork** [comment]
Ah, okay that works - don't think that's documented anywhere. Works only with native frame enabled.

So --- how about putting the most important things in the tray menu *if native frame is disabled* ? (I could do that)

**Comment by MarshallOfSound** [comment]
If native frame is disabled that menubar can still be accessed through shortcuts

**Comment by MightyPork** [comment]
Um... no? Might be platform specific, but pressing alt without native frame does nothing.
