### ISSUE TITLE
Google 5-star Ratings - Enhancement Request

### ISSUE THREAD

**Issue by amc2002** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#584]
Putting in an enhancement request - Google 5-star ratings

According to this post and example script, Google is still saving Google Play Music 5-star ratings:
http://bit.ly/22fWCQO

If you add the script above using TamperMonkey, the old 5-star ratings actually show in Google Play Music, but the rating system is broken.

Google, in its infinite wisdom, has removed the rating feature from all Google Music apps, opting instead for a simple thumbs-up/thumbs-down system, enraging paying subscribers:
http://bit.ly/1SN34fy

Though you can no longer use the script above to rate tracks, the Prime Player extension for Chrome apparently still enables rating of Google Play Music tracks, as long as the track is actively playing.

I'm wondering if there is a way follow these clues and re-add the 5-star rating system to your standalone player? It would be fantastic for so many of us who spent hours and hours rating our tracks.

**Comment by SicariusNoctis** [comment]
It's uncertain how long those ratings will persist. Google might decide to remove them tomorrow.

However, I do want ratings (it's one of the reasons I'm reluctant to switch completely from MusicBee). A _local_ database which would keep track of our ratings would be pretty nice. However, I'm willing to bet this isn't yet core functionality that the majority of users desire/need. (Google didn't make their decision willy nilly!)

**Comment by MarshallOfSound** [comment]
As @SicariusNoctis Google doesn't make decisions for the fun of it so removing this lab must have been for a good reason based on reasearch into their user base.

I don't exactly want to go hacking around inside the GPM rating system as that can negatively affect which songs users get to listen to if / when it breaks because Google removed something.

For now, I am going to stick with the philosphy that undoing Google changes is not a good plan :+1:
