### ISSUE TITLE
Javascript Error on Opening (Linux)

### ISSUE THREAD

**Issue by smilligan93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#592]
**OS:**
Arch linux, aur package that pulls directly from the git repo [https://aur.archlinux.org/packages/google-play-music-desktop-player-git/](here)

**Issue Descriptions:**
Opening the program leads to
```
 Uncaught Exception:
TypeError: Cannot read property '0' of null
    at /usr/share/google-play-music-desktop-player/resources/app/build/index.js:97:19
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/index.js:96:39)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7).
```

No windows appear when initially ran, just this popup. If I try to run the program again a window appears that is just black. Tried with '--disable-gpu' and still not working. The issue appears to be in the assignment of 'position' a couple lines above and is assigned null.

**Steps to Reproduce:**
Open the program on arch (unable to test on different distro).

**Side note**
I was able to get the program to open by putting 
```if (position != null) { 
_electron.screen.getAllDisplays().forEach(function (display) {
...
});
}````

Which then produces another js error on open:
```Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/keyboardShortcuts.js:17:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/index.js:3:1)
    at Module._compile (module.js:425:26)```

but the app still opens and plays music, but unable to access "Desktop Settings" in the side bar.

**Comment by MightyPork** [comment]
I can confirm this bug, it started with commit 1e241cb, before that it works OK.
All commits past that are broken for me.

![screenshot_2016-03-14_21-06-20](https://cloud.githubusercontent.com/assets/2041118/13758293/0825a640-ea29-11e5-81c5-7c65b54402c4.png)

If I could suggest something, why not make a "development" branch and put experimental stuff there, instead of straight to master?

This'll be an issue especially with Arch, but also everyone running it from git, thinking that master = stable. (including me - good catch with this, at least I know not to update yet!)

**Comment by BrianAllred** [comment]
Also confirmed. As package maintainer for the AUR pkgbuild, I can force the checkout for the commit prior to this one, should fix it for Arch users.

I'm with MightyPork, though, maybe create new branches for each version release? Or at least mark the last commit to make it into a release? That way users can clone a specific branch or commit to build more stable versions. Just a suggestion, though. Keep up the great work!

**Comment by MarshallOfSound** [comment]
The position issue I thought I had fixed, turns out it was in a stash somewhere on my local machine
The object has been destoryed error is an electron issue, I have raised it here --> https://github.com/atom/electron/issues/4800

As for different branches and such, my current methods for working on a project mean that unless the commit is tagged with a version number, master cannot be taken as being "stable".  If you want a stable checkout from git, checkout to the latest tag.

**Comment by MarshallOfSound** [comment]
@BrianAllred You should try checkout the latest tag as part of the AUR build, it would solve a lot of problems

**Comment by BrianAllred** [comment]
Ah, wasn't aware of tags. Thanks for the heads up.
