### ISSUE TITLE
Feature request: Offline cache

### ISSUE THREAD

**Issue by martinloucka** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#596]
I know this is probably a long run goal and not some simple tweak to add, but maybe more people would be interested so I'll give it a try. 

Since I travel a lot, there are some blind spots where I can't or really don't want to connect to the Internet - in fact, many of them. It would be perfect if the app could work off-line (similarly to e.g. iOS version). I'm not sure whether it is even possible through the API, but I have hundreds of songs uploaded to Google Play Music to have them so to say in one place and slowly I'm begining to use GPM as my primary music player (instead of iTunes). But what really bothers me is total lack of cache for the Windows platform. 

So at least regarding the bought/uploaded songs which are DRM-free and available for download, would it be possible to turn the application into off-line desktop player? Either it could be downloaded in the application cache from Google (whereto I've uploaded files from my disk before), or maybe it could look to chosen disk location and merge the music (though the first option would be better I think).

In any case thanks a lot for your great work, I guess it made loads of people very happy!

Martin

**Comment by MarshallOfSound** [comment]
This is currently not technically possible and if I enabled it "somehow" I would almost certainly be in preach of legal rules somewhere :-1: 

So unfortnuately no, this is now going to happen

**Comment by alex4u2nv** [comment]
Maybe it can be integrated with the APIs that support Google Play Music Manager?

**Comment by lucidBrot** [comment]
Four years have passed since this feature request was opened. Perhaps it was different back then, but currently it is possible to grab all the music from the [settings](https://play.google.com/music/listen#/accountsettings) in the official google play music website. So I doubt it would be an issue to do that and use it for offline listening.

I'm interested in this feature for two reasons:  
* No more lag caused by listening to music while gaming
* Ability to use local files with higher quality than the compressed thing google stores. I have uploaded many lossless files that are only 320bpm on gpm.

In fact, those are the only reason I am looking for a custom player.
Do you still think this cannot be done?
