### ISSUE TITLE
Event log message indicates that the Windows Installer reconfigured all installed applications

### ISSUE THREAD

**Issue by USAuser73** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#598]
Hi.  I noticed the following.  On start up I noticed all of my applications reconfigured themselves.

https://support.microsoft.com/en-us/kb/974524

Microsoft released this:

Cause

This problem can happen if one of the following is true:

You have a group policy with a WMIFilter that queries Win32_Product class.
**You have an application installed on the machine that queries Win32_Product class.**

Note For more information about WmiFilters please refer to: KB555253 - HOWTO: Leverage Group Policies with WMI Filters
Resolution

If you are using a group policy with the WMIFilter that queries Win32_Product, modify the filter to use Win32reg_AddRemovePrograms. 

If you have an application that makes use of the above class, please contact the vendor to get an updated version that does not use this class. 

To narrow down the application that is causing the problem, you can follow the "Clean boot" troubleshooting method in the following article in the Microsoft Knowledge Base: 

How to troubleshoot configuration errors by using the System Configuration utility in Windows XP (http://support.microsoft.com/kb/310560)

**Comment by jostrander** [comment]
Looks like it's being used as part of the upgrade path from the old gpmdp to the new electron version: Google-Play-Music-Desktop-Player-UNOFFICIAL-/src/old_win32.js

**Comment by MarshallOfSound** [comment]
My question here as per #543 , although it looks like you have done more research and actually found root cause (*claps* @jostrander )

Is this actually an issue?  The code (and the call to `wmic` is required in order to uninstall the old version.  I might be able to limit the number of calls a bit more (E.g. call once and never again)  but the call still needs to be there.

**Comment by jostrander** [comment]
I would assume something in win10 is notifying users of this otherwise there wouldn't be bug reports, because I highly doubt two windows users just happened to be poking around reliability monitor. I'm not sure if it's actually causing any direct side effects, but to limit future reports maybe add a flag to make sure it's only ran once?
