### ISSUE TITLE
Kill Flash

### ISSUE THREAD

**Issue by tasmo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#60]
Marshall is OpenSource which is very great. Instead of using Adobe's closed source Flash player the WebKit might be able to play Google Music files through HTML5 like discussed below:
https://github.com/radiant-player/radiant-player-mac/issues/335

**Comment by MarshallOfSound** [comment]
Short answer, it can't at the moment.  For a multitude of factors, the key of which bring a DRM library that is only in chrome.

I always watch this because o hate flash as much as the next guy, but until chrome either opens up or loosens up their DRM we can't use HTML 5 audio.

At least that's my understanding :P

**Comment by MarshallOfSound** [comment]
No point having this issue persist, when I can I will implement, until then it is a `won't fix` / `can't fix`

**Comment by MarshallOfSound** [comment]
@tasmo Stay tuned for #171 `3.0.0` 

Flash will be KILLED :+1:

**Comment by tasmo** [comment]
@MarshallOfSound Wow, sounds great! 👏🏽
