### ISSUE TITLE
Mouse back/forward buttons do not navigate.

### ISSUE THREAD

**Issue by slowbro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#745]
**OS:** Arch Linux x64, i3wm
$ uname -a
Linux xb 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
$ i3 -v
i3 version 4.12-10-g6fb271f (2016-03-11, branch "makepkg") © 2009 Michael Stapelberg and contributors
$ pacman -Q | grep google-play
google-play-music-desktop-player-git 3.0.1.56.g7759ce7-1

**Issue Descriptions:**
Mouse forward/back buttons do nothing in GPMDP. I would expect them to let me navigate like in the browser. Pressing backspace seems to work - just not the mouse buttons.

**Steps to Reproduce:**
1. Open GPMDP.
2. Navigate to any artist/album/anything.
3. Try to click the 'back' mouse navigation button.
4. Notice that nothing happens.

**Other Info:**
Here is the ButtonPress events skimmed from `xev` for forward:
```
ButtonPress event, serial 33, synthetic NO, window 0x2200001,
    root 0x76, subw 0x0, time 6808564, (-1,281), root:(1283,833),
    state 0x10, button 9, same_screen YES

ButtonRelease event, serial 33, synthetic NO, window 0x2200001,
    root 0x76, subw 0x0, time 6811178, (-1,281), root:(1283,833),
    state 0x10, button 9, same_screen YES
```
For backward:
```
ButtonPress event, serial 33, synthetic NO, window 0x2200001,
    root 0x76, subw 0x0, time 7014240, (7,319), root:(1291,871),
    state 0x10, button 8, same_screen YES

ButtonRelease event, serial 33, synthetic NO, window 0x2200001,
    root 0x76, subw 0x0, time 7014364, (7,319), root:(1291,871),
    state 0x10, button 8, same_screen YES
```

Let me know if you need any more information!

**Comment by jostrander** [comment]
Unfortunately electron doesn't expose any API for linux to allow use of the extra buttons on the mouse. The only other solution would be for a native module built for linux that would capture those buttons similar to what @MarshallOfSound did for windows media keys in windows.

**Comment by slowbro** [comment]
Ah, OK. I didn't realize that had happened. My media keys seem to work under Linux as it stands, so that's seemingly already fixed by the same patch?

**Comment by jostrander** [comment]
If they worked before, you didn't have anything already intercepting those keys. If, however, you use Gnome then it was stealing your media key bindings and the only way to play nice is to use D-Bus to listen for the media player key events, otherwise you have to disable the media keys in gnome, and use the exclusively in GPM. At least that's what I came to understand on Ubuntu 14.04 Gnome. Other distributions may vary. 

If I had a mouse with the extra buttons, I would try to debug and see if this is something I could implement, but from research it appears that the only way electron will support it is via the app-commands event emitter in windows, or a native node module that will listen for the buttons.

**Comment by nkneer** [comment]
I am far from as technically proficient as the rest of you, but using my mouse navigation buttons set for "Forward" and "Back" produce an uncaught error: 

An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Tue Mar 29 2016 10:36:22 GMT-0400 (Eastern Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\NKneer\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\NKneer\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
@nkneer That exception is for windows so not relevant to this issue :+1: 

That exception has been fixed in master

**Comment by slowbro** [comment]
@jostrander AFAIK it never worked. I shouldn't have anything grabbing those keys (since they are more program-specific than system-wide like the media keys).

I've never done any Node, but if someone can point me in the right direction for debugging, or what part handles key presses etc I can see what I can do.

**Comment by jostrander** [comment]
@slowbro Specifically what I was saying is the patch that I submitted for linux media keys was for Ubuntu/gnome media keys only and had nothing to do with anything else. 

The issue specifically is that node doesn't have any way to grab those extra mouse buttons, and neither does the GPM web page. What is actually listening for the buttons in applications like Chrome is OS specific code written in C, CPP, or whatever they use. In order for GPMDP to be able to processes those keys some platform specific code will have to be written and compiled so that node can receive the events and act on them, because currently node doesn't even know they exist.

**Comment by jostrander** [comment]
Specifically what mouse do you have, and how many buttons does it have? Your `xev` output above is buttons 8 and 9, which are above the standard 7 button standard. Do you have specific software installed to manage your mouse? Are you using anything such as XBindKeys,  xvkybd, or similar?

**Comment by slowbro** [comment]
I have a Logitech M510. It is the unifying receiver type, but generally a normal mouse. It has a scroll wheel and two side buttons. I mapped all buttons, and it looks like this:

Button 1: Left Click
Button 2: Middle Click (scroll wheel straight down)
Button 3: Right Click
Button 4: Scroll Up
Button 5: Scroll Down
Button 6: Push scroll wheel to the left (towards left mb)
Button 7: Push scroll wheel to the right (towards right mb)
Button 8: "Back" nav button
Button 9: "Forward" nav button

I have nothing special set up as far as x config. I just plugged the mouse in and went with whatever it gave me.

**Comment by jostrander** [comment]
Alright, I used xmodmap to map my 6-7 buttons to 8-9 so its registering as back/foward in chrome correctly. I'll try to debug and see if I can get anywhere in GPMDP.

**Comment by slowbro** [comment]
Thanks! Let me know if I can help in any way :)

**Comment by jostrander** [comment]
I create a native node module for this, now I just have to see if it's stable enough integrate into this project.
