### ISSUE TITLE
[Enhancement] Scrobble to Libre.fm

### ISSUE THREAD

**Issue by 0nse** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#769]
Consider supporting [Libre.fm](https://libre.fm/). It uses [Last.fm's old scrobbling API](http://www.last.fm/api/submissions). All calls simply have to be sent to http://turtle.libre.fm/ insetad of http://post.audioscrobbler.com.

**Comment by jostrander** [comment]
Will the hosts file trick work that's listed on http://turtle.libre.fm? Aka putting `213.138.110.190 post.audioscrobbler.com` in your hosts file to redirect to libre.fm?

**Comment by 0nse** [comment]
This will most probably work. However, I am using both services simultaneously. Thus, I want to be able to submit tracks to both.

**Comment by MarshallOfSound** [comment]
@0nse The API it supports is deprecated on last.fm's side of things.  So I have implemented the new API (v2), this means it isn't a simple hosts file change or a simple code change.  It would involve adding a bunch more logic and supporting `libre.fm` doesn't appear to be standard (yet).

I'll look into supporting it with our last.fm logic but because the API's are different don't hold out :+1:

**Comment by MarshallOfSound** [comment]
I had some time to look into this recently and unfortunately the API's are quite a bit different and having two implementations would be quite messy.  last.fm seems to be the main one at the moment so we will stick with them till that changes
