### ISSUE TITLE
Feature Request: Song title in task bar

### ISSUE THREAD

**Issue by jonfroese55** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#77]
Loving your app so far, just switched over to GPMAA and loving it for the most part. I despise web players so your app was the perfect thing for me.

One very small thing, that I noticed moving from the Spotify desktop app is this:

![spotifygpmaa](https://cloud.githubusercontent.com/assets/12867865/11605475/1374d5d2-9ac6-11e5-9366-3e4bde9e7ea7.png)

Looking at the task bar, the spotify player will display the currently playing song, but the Google player doesn't.

I usually find this pretty useful when I'm playing a windowed game, or just browsing the web, I can glance down and see what song is currently playing.

Would be a nice feature to have. Otherwise great app!

Edit: Just realized this works with notifications enabled. I don't really want the notifications enabled, but it is a workaround I suppose, changing the feature request for this to update without notifications needing to be enabled.

**Comment by MarshallOfSound** [comment]
I was just about to blast you to high heaven because this feature is implemented, but then I read your comment and double checked the code.  Seems like a small error in some if logic, the JS only sends the song change event if the desktop notifications are turned on.

I'll just move the if logic so it works without notifications enabled :cactus:

**Comment by jonfroese55** [comment]
I figured it was something very simple like that, thanks for looking into it
