### ISSUE TITLE
Close button is not clickable when moving mouse to the upper right.

### ISSUE THREAD

**Issue by sebastianhaeni** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#784]
**OS:**
Windows 10 Pro x64

**Issue Descriptions:**
Close button is not clickable when moving mouse to the upper right corner of the screen. The button has some margin to the right. Moving the mouse to the upper right is a pattern in Windows that allows the user to get to the close button very fast without having to make a precision move to get to the button.

**Steps to Reproduce:**
Maximize window. Move mouse to upper right corner. Click. Nothing happens. Move mouse a few pixels to the left. Click. It closes.

**Comment by MarshallOfSound** [comment]
It is literally 4 pixels, assuming a 1080p screen you have an `0.208%` chance of hovering over that portion of the screen.  Compared to a solid 2-3% chance of getting the actual close button.  

This border is actually required due to a technicaly limitation of electron to do with mouse over and hover states.  As some important person once said "if you do silly things (clicking something that isn't the close button), dont expect clever results" :+1: :cactus: 

Closing due to technical limitations
