### ISSUE TITLE
Uncaught Exception: UNKNOWN: unknown error, open 'C:\Users\*\AppData\Roaming\Google Play Music Desktop Player\json

### ISSUE THREAD

**Issue by henriquejandrade** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#831]
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Tue Mar 29 2016 14:58:24 GMT-0300 (E. South America Standard Time)

#### Error:
*UNKNOWN: unknown error, open 'C:\Users\*\AppData\Roaming\Google Play Music Desktop Player\json*
```js
Error: UNKNOWN: unknown error, open 'C:\Users\*\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (C:\Users\*\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\utils\PlaybackAPI.js:74:22)
    at PlaybackAPI.setTime (C:\Users\*\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\utils\PlaybackAPI.js:114:12)
    at EventEmitter.<anonymous> (C:\Users\*\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\utils\PlaybackAPI.js:48:15)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\*\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\api\lib\web-contents.js:134:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by timnolte** [comment]
+1

**Comment by MarshallOfSound** [comment]
This appears to be a read / write issue at the OS level.  `unknown error` is not very descriptive *claps for node*

Unless it happens again / frequently there is not much I can do here

**Comment by timnolte** [comment]
This is constantly happening for me. And your error windows don't have a close button so my only option to dismiss them is to submit an error report. You need to test this running as a limited user on Windows after installing via elevated privileges. If this is a write issue as you say then I suspect you aren't writing to the filesystem to appropriate place for standard users. Are you writing to the install directory? That would be bad practice.

**Comment by MarshallOfSound** [comment]
@timnolte Hmmmm, if you run as admin (And then the program makes temporary files like settings and such) and then run as a limited user.  What do you think is going to happen? :+1: 

I am not writing to the install directory, but windows file permissions means if you create as admin and then try write as a standard user it won't work.  This is just basic OS level file permissions

**Comment by timnolte** [comment]
@MarshalOfSound no proper Windows applications account for environments where they get installed as an administrative user but should run as a standard user only writing files to the current running users AppData directory. Windows applications, especially a media/music player, shouldn't require admin privileges to run properly. The only way for apps to be installed on Windows machines is via an admin account. A standard user on the system should be able to run the application after install without errors.

**Comment by MarshallOfSound** [comment]
@timnolte Incorrect, you can install this application without admin rights and that is its intended usage.  You broke this applications installation flow by deliberately running as admin when it wouldn't have prompted you to do so.

Look into how Squirrel works and you will see what I mean

**Comment by MarshallOfSound** [comment]
The best I can come up with here is to possibly `chmod` (and the windows equivalent) the settings and playback API files to ensure I can always write to them.  But a user shouldn't be randomly decided whether or not to run as admin

**Comment by timnolte** [comment]
@MarshallOfSound no, I did not deliberately install as an admin user. The only thing I did was double-click the installer and was immediately prompted to enter authenticate as an administrative user in order to proceed with the install. I'm running on Windows 10 Professional I should add. My login is a Standard user. I'm also on a domain.

**Comment by MarshallOfSound** [comment]
@timnolte Hmmm, OK which version did you initially install.  This could be a completely separate problem...

By default the uploaded installers do not require admin rights

**Comment by timnolte** [comment]
@MarshallOfSound I want to be clear that I'm not running the application under elevated privileges, I only installed as an admin user. Settings files shouldn't be under the install directory if that's what you mean, they should be under the current running users AppData. As for the version I installed, it came from http://www.googleplaymusicdesktopplayer.com , clicked on the "Download Latest - 3.0.1" button,  then "Windows", which gave me an x86 installer. BTW, I'm running a 64bit Windows 10 Pro.

**Comment by MarshallOfSound** [comment]
@timnolte Yep, I get you didn't run under elevated.  But you said you ran the installer under elevated privileges which then launched the app.  By privilege inheritance the app (on first run) ran under elevated privileges.

The core issue here is why you had (or were at least prompted) to start the installer as an administrator because it shouldn't EVER require admin rights EVEN during the install process.  I have just double checked the raw `3.0.1` installers and can confirm that they do not require admin rights.  Can you double check that it automatically prompted you for admin rights, and then ensure that the installer is correctly signed by me.

You can check the signature by right clicking on the installer and choosing properties.  Then choose the "Digital Signatures" tab and check that "Open Source Developer, Samuel Attard" is the ONLY signature.

**Comment by timnolte** [comment]
@MarshallOfSound since this issue is on my work computer I will check it tomorrow when I get in the office. I'm surprised you say that admin rights should never be required. This leads me to wonder, is the application getting installed to the users AppData and not the system Program Files? If that's the case then that is the problem, our company machines don't allow applications to be installed by users in their AppData directories. And I was pretty sure Standard Users have never been allowed to install applications even since Windows XP.

BTW I'm not trying to be a jerk about this. I totally get that you are doing this in your spare time. It's just frustrating to report an issue, that is not only annoying but almost makes navigation within the app unusable, to have the developer just respond to the equivalent of "too bad".

**Comment by MarshallOfSound** [comment]
@timnolte The initial automatic report was somewhat undescriptive, it took a few comments before I even could diagnose it came down to some form of a permissions error.

The application is indeed being installed to AppData, this is the main functionality of Squirrel and allows auto updating and non admin installs which makes for a much better user experience.

How can your company block applications being installed into AppData?  It clearly kinda worked because you got to the point where an automatic error report could popup in the UI.  I just pushed a patch that should fix this strange admin perms issue, but it will only patch for new users (some things just can't be backwards compatible).

**Comment by timnolte** [comment]
@MarshallOfSound so at our company AppData is protected via Group Policy, in order to protect against cryptoware. From a security standpoint allowing users to install applications to data locations just doesn't seem like good practice. This does explain the prompt for an admin account then. I understand the reasoning, actually it's exactly the use case of allowing a Standard User to install something their system wouldn't normally let them install.

**Comment by MarshallOfSound** [comment]
Oh, so from what I can tell (and I bit of guess work) the application fails to install to AppData so it falls back to a standard `Program Files (x86)` install which requires admin rights.  I have like never seen that before :/

I'll try simulate the scenario on a VM and probably end up raising an issue over at Squirrel.Windows

**Comment by jostrander** [comment]
@timnolte Can you confirm the location of your install? Did the administrative privileges allow you to install into AppData since it's protected?

**Comment by timnolte** [comment]
@MarshallOfSound cool, thanks for your time spent. And excellent work on the application, even in spite of my frustrations. ;-)

**Comment by MarshallOfSound** [comment]
@timnolte Yeah, what @jostrander said :smile: 

Where did it actually end up?

**Comment by jostrander** [comment]
@MarshallOfSound Will this work with the current installer to do a machine wide install to program files? https://github.com/Squirrel/Squirrel.Windows/pull/337

**Comment by MarshallOfSound** [comment]
@jostrander Technically I think that is what is already happening.  I remember reading somewhere (can't find it now) that if an install to AppData fails it falls back to an admin permission required install to Program Files.

One of the commits in that PR is named to that affect

**Comment by jostrander** [comment]
It looks like if `%LocalAppData%` fails to write it will install into `%HomeDrive%\ProgramData\` then under a user context because `Program Files` will always require a UAC prompt to update the app, which Squirrel absolutely refuses to do. Just reading through the issues/PR's there is a bit of a mess. There was also a [merged PR](https://github.com/Squirrel/Squirrel.Windows/pull/337/commits/e37b9af72fa592b858956c8f52874cd0e1d1124b) that changed the install directory automatically if UAC was elevated.
