### ISSUE TITLE
Feature: Resizing list columns

### ISSUE THREAD

**Issue by SpectralKH** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#849]
So, I got a feature request; Resizing the columns you see when you browse Google Play Music. The reason I want this is the way Google resizes now, does not take text length into account, and I often end up with this;
![screen shot 2016-03-30 at 20 30 08](https://cloud.githubusercontent.com/assets/11315492/14153071/a6dd6ad6-f6b6-11e5-82bc-125e6490b8a4.png)
Often, most of song titles are pretty hidden, which is not ideal. You see how I can't even see full song titles, while the Artist/Album columns takes up 500 pixels.

Also, just wanted to say that this client is awesome! Had to move from iTunes to get the Android support, and there wasn't any music library client that suited me - Until I found this :) Absolutely love it :D

**Comment by MarshallOfSound** [comment]
This is something that is very subjective and was obviously a design decision thought out by google.  Although I get your point that in some cases (song names being long and album names being short) it is very wasteful of space.  I don't want to hackily "fix" an issue that

a) Could be reversed (short song name, long album name)
or worse
b) Fixed by google themselves at some point which breaks literally everything

For now, I'm sorry, but struggle onwards, against the oppression that is white space :+1: :cry: :egg:

**Comment by SpectralKH** [comment]
@MarshallOfSound To be honest, I don't see the problem with a draggable line in the list's header to make people's lives a little easier. Neither do I see how this is a "hackily fix," as if the customized keyboard shortcuts isn't the same thing.

And in response to a), an example is "Language For Now (feat. Skrillex, Diplo, Justin Bieber, Porter Robinson, Deadmau5 & Kaskade)". I don't blame the artist for that, there's obviously not much you can do, besides removing artists completely - Which is a worse trade-off.

Also, I'd like to add that, the longest titles, you don't even have a way to see full titles of (Well, pressing "E"), since the box's with is capped at 1800px, as you see here;
![screen shot 2016-04-01 at 16 18 09](https://cloud.githubusercontent.com/assets/11315492/14209617/5b0e1572-f825-11e5-8b2a-01bf4496e184.png)
However, that is another thing you could do; Removing the max width. That's literally just one line to change.

**Comment by MarshallOfSound** [comment]
@SpectralKH To explain my reasoning a bit more in depth

Let's say I implement a drag-able line to re-size the columns.  The process for making that work would be something like.

1. Add pseudo `:after` elements on all the table cells to simulate a draggable border on the table columns
2. Listen for mousedown events and mouseup events and handle the horizontal "delta" as a drag.
3. Save this delta and restore it every time a page with a table like that is loaded.

Sounds simple enough, with a bit of free time I could probably do it.  But the problem I have with this is that it has the potential to break the UI completely.  Let's say google then implement it their own way, I can guaruntee that would break all sorts of things in all sorts of ways.  This is different to features like (as you mentioned) keyboard shortcuts.  Because if google changes things the keyboard shortcuts simply won't work, but it won't break the app.

I am sure Google (as with basically all dev companies) goes through a UI / UX review and tests their products on a massive array of devices with a massive array of form factors.  Messing around with things like column widths and max-widths could have untold side effects on screen sizes or user stories that I know nothing about.

I'm not trying to shoot down your requests in flames and laugh as it burns, but I am trying to explain my logic as to why I think it's a bad idea.  I'm open to objections to my points.

**Comment by SpectralKH** [comment]
@MarshallOfSound I clearly see that the chance of stuff breaking is a big possibility, and if you don't got the time for it, that's not a problem. But on the other hand, I want to say that it's probably not going to happen - It would not be a highly requested thing since their targeted audience is more mainstream. That is not to say that they change anything else that breaks it, but in that case, I suggest having the feature as something disabled by default, thus it would be more like the shortcuts; It wouldn't break the application, just a feature. Taking it to the next level would be disabling it off automatically if something like this ever occurs.
