### ISSUE TITLE
Request: Spam now playing info to IRC Client

### ISSUE THREAD

**Issue by j0nnymoe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#88]
Send Artist - Song to irc chat via /nowplaying command in hexchat.

**Idea -  if possible to emulate foo_winamp_spam.dll plugin for foobar200, no need to develop any plugins for any irc clients alot of them already have plugins for this method**

https://github.com/RazielZ/foo_winamp_spam

**Comment by MarshallOfSound** [comment]
Currently out of scope, their are programs out there that can read what song is currently playing through the title of this app.  Maybe you can try hooking one of those into this, either that or custom build this project and make the integration yourself.

Only out of scope due to the low potential userbase, the high complexity and my desire to keep this program simple and bare bones :)
