### ISSUE TITLE
Remember window size when closing

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#9]
It would be nice if the player remembered the window size (and perhaps position?) upon closing and restores this next time the app is opened (rather than initialises at the default 1080x720)

**Comment by MarshallOfSound** [comment]
Remembering the window size shouldn't be too tricky.  

Position I'm kind of against due to the unpredictable nature of the users screen setup.  For instance devices with a secondary screen plugged in would be very confused when the secondary screen is unplugged and then the app tries to position itself on it.

**Comment by hndmrsh** [comment]
Yeah, it's mostly the size I was concerned about. I was thinking about what other applications do with regards to position, and I think most try to position themselves on the monitor that application was closed on. Would it be worth trying to position the application in the position it was closed, and falling back to the primary monitor (or default startup position) if that screen is not available?

**Comment by MarshallOfSound** [comment]
Personal note on this issue
* Will need two different positions / dimensions saved (One for mini one for maxi)
* Will need to check if the position is valid
* Should use the WinForm built in user settings library

**Comment by MarshallOfSound** [comment]
In master
