### ISSUE TITLE
media buttons not working on my logitech keyboard

### ISSUE THREAD

**Issue by superjase** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#90]
my play/pause, stop and skip buttons do not work for the player. these buttons work perfectly in other players (such as vlc, winamp).

**Comment by MarshallOfSound** [comment]
I have tested this with the only logitech keyboard I have (a K260) and it works perfectly fine.  Can you please confirm which keyboard you have?

**Comment by superjase** [comment]
it is a logitech wave 2.4 cordless keyboard running setpopoint 6.67.83 and driver 5.90.41

**Comment by MarshallOfSound** [comment]
Can you use something like Auto Hotkey to see what key is actually being received the computer

**Comment by superjase** [comment]
hi. i think it has something to do with the (stupid) way setpoint handles the media keys. see the following links:
http://tomse-blog.blogspot.co.za/2014/11/logitech-setpoint-and-media-keys-not.html
http://www.mediamonkey.com/support/index.php?/Knowledgebase/Article/View/49/2/multimedia-keyboard-buttons-dont-work

are you able to work out what line i need to add to my players.ini file?

**Comment by MarshallOfSound** [comment]
I have no idea mate, try the first fix on that page, or use autohotkey

This is confirmed as not being my fault / problem.  Good luck :smile_cat:

**Comment by Devo7v** [comment]
I just wanted to chime in here since I was having the same problem.  I installed UberOptions and set all three of the media keys to "Other:Generic Button ".  Play/Pause, Next, and Previous all work regardless of if GPMDP has focus or not.  I suggest installing UberOptions, just be aware that you will have to set up all your settings in SetPoint again.
![screenshot 1](https://cloud.githubusercontent.com/assets/15945504/11879200/f3a46fa4-a4c7-11e5-8b08-0265154765ec.jpg)

**Comment by superjase** [comment]
thank you so much!!! this has solved my problem 100% :)
