### ISSUE TITLE
No ASIO4ALL in devices list

### ISSUE THREAD

**Issue by keerah** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#922]
OS: Windows 10
Issue Descriptions: No ASIO4ALL in audio devices list

When ASIO4ALL installed it's impossible to choose it as audio output, no such item in the list
Other programs work well with it
ps. No WASAPI devices present in the list as well

**Comment by MarshallOfSound** [comment]
Does it appear as a sound device in your "Playback Devices" menu.

You can reach that menu by right clicking on the volume icon in the tray and clicking "Playback Devices"

**Comment by keerah** [comment]
No it doesn't. 
But other audio software like Foobar player has it in audio outputs list along with ASIO and WASAPI
I think it's important for any player to be able to use ASIO

**Comment by MarshallOfSound** [comment]
If it doesn't appear in that list it is not considered a system audio device and I have no idea how other programs would pick it up.  Regardless, it not appearing is a limitation caused by fundamental chromium code which I have 0 control over and 0 ability to attempt to patch.  I would suggest raising an issue over on the chromium forums if you want ASIO support in chromium

**Comment by keerah** [comment]
I see. Thank you, that's already done :)

**Comment by j-potts** [comment]
@keerah I know it's been a while, but I'd also love to see ASIO support for this project. Would you happen to have the Chromium issue for ASIO support handy?

Thanks!
