### ISSUE TITLE
[Ubuntu] Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by jweede** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#931]
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.1.0
**Time:** Mon Apr 11 2016 10:47:34 GMT-0400 (EDT)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:476:9)
    at process._tickCallback (node.js:382:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment]
This one is quite obvious really, you turned on the PlaybackAPI and you already have something running on port 5672

**Comment by jweede** [comment]
Thanks, @MarshallOfSound. The error message in the application doesn't indicate this. Only after I click the 'report' button do I see this error. 

I was wondering if a proper error message would be more appropriate.

**Comment by MarshallOfSound** [comment]
@jweede The problem is like 99% of users will have no idea what the error message means and will not want to see it in the slightest.  I wrote the error popup with a generic user in mind not a dev who knows what they are doing :+1: 

On linux you can actaully get a more dev style experience by running the player with the `--dev` command line flag.  That way you get these errors in the console and such

**Comment by jweede** [comment]
Thanks again @MarshallOfSound. Great work, btw. :+1:
