### ISSUE TITLE
Media keys rarely work

### ISSUE THREAD

**Issue by mholmPurdue** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#955]
**OS:** 
 Windows 10 1511, 64bit, Intel CPU.
**Issue Descriptions:** 
Media keys work about 10% of the time. Even if chrome isn't running. I can rapidly spam my media keys, or use them as normal, and it takes about 10 presses before the button actually registers to the application. Holding the media key has no effect. Hardware confirmed working.

I use a logitech G600 for media keys, so this MAY be a concern, but everything worked correctly yesterday

**Steps to Reproduce:**
1. Play Media
2. Attempt to use media keys
3. Repeat step 2 till music pauses/plays

**Comment by jostrander** [comment]
Do you have the Logitech software set up for your keyboard? If so can you
disable it and see if it fixes your media keys?
On Apr 17, 2016 5:52 PM, "mholmPurdue" <notifications@github.com> wrote:

*OS:*
Windows 10 1511, 64bit, Intel CPU.
*Issue Descriptions:*
Media keys work about 10% of the time. Even if chrome isn't running. I can
rapidly spam my media keys, or use them as normal, and it takes about 10
presses before the button actually registers to the application. Holding
the media key has no effect. Hardware confirmed working.

I use a logitech G600 for media keys, so this MAY be a concern, but
everything worked correctly yesterday

*Steps to Reproduce:*
1. Play Media
2. Attempt to use media keys
3. Repeat step 2 till music pauses/plays

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/955>

**Comment by mholmPurdue** [comment]
It's a logitech mouse, so I can't use media keys without it, I'll try setting something up in Autohotkey to simulate media keys

**Comment by mholmPurdue** [comment]
Looks like it was the logitech drivers, sorry
