### ISSUE TITLE
Missing About section. 

### ISSUE THREAD

**Issue by ccolorado** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#963]
**OS:** Linux

**Issue Descriptions:** Finding the either the homepage or github repo is harder that it needs to. The app name is generic enough that you get hits form all over the internet, from the google play store, to tutorials and comparisons of online services. About section is either missing or very hard to find. 

**Steps to Reproduce:** Try to find an About Section in the application.

**Comment by MarshallOfSound** [comment]
@ccolorado I'm not sure what you are asking for here, or what you think the issue is,  If you google search

* "google music desktop" the website is the 6th result
* "google play music desktop" the website is the 3rd result
* "google play music desktop player" the website is the 3rd result
* "playmusic desktop" the website is the 3rd result

There is only so much SEO I can do, and in most cases I won't be able to beat Googles own websites in their search results... ???

**Comment by ccolorado** [comment]
Yeah I guess I could have been a little more descriptive. 
Most desktop applications have "About *" Sections on their menu.

I didn't mean't to go to try to rate higher on google. Just a local way to reference the application's landing page. 

Here is the [skype](http://imgur.com/wa1C0ub) section as an example.

**Comment by MarshallOfSound** [comment]
Oh, you can access our about menu from the tray icon. :+1:
