### ISSUE TITLE
Phantom border on second monitor

### ISSUE THREAD

**Issue by lech** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#978]
**OS:**
Running the latest build downloaded yesterday on Win7 x64, Dark Theme

**Issue Descriptions:**
When the player is maximized under multiple monitors a phantom border appears on the monitor to the left. In this case, two 1080p monitors in left/right respectively. When the application is maximized on the right hand monitor, the right edge of the left monitor displays a phantom border.

Note that the border in question is roughly the same height of the application when windowed. Vertically resizing in windowed mode then maximizing presents you with a phantom border of roughly the same height before maximizing.

**Steps to Reproduce:**
1. Open the player and make sure it's windowed and not maximized in the right hand monitor.
2. Take note of the height of the player window.
3. Maximize the window.
4. Observe a new phantom border along the right hand edge of your neighboring monitor to the left.
5. Resize the window and repeat as necessary.

**Comment by TorgeirHolm** [comment]
I see what is probably the same thing on Windows 10, Dark Theme

**Comment by lech** [comment]
Just to confirm, this also happens under the light theme as well as with any other custom theme options.

**Comment by TorgeirHolm** [comment]
_Posting this screenshot here too, since it is relevant to this thread as well._

You can see the 8px ghost border on the left hand side in the screenshot taken while maximized on my rightmost 1920×1080 monitor. Note that the screenshot dimensions are are 1928×1090 – apparently there are black borders above and below as well.

![screenshot 2016-04-23 12 42 26](https://cloud.githubusercontent.com/assets/18615991/14760963/6d1fe57c-0952-11e6-98ab-4f35430cf3a5.png)

**Comment by MarshallOfSound** [comment]
Raised upstream https://github.com/electron/electron/issues/5267

**Comment by lech** [comment]
Enabling the option to use the system windows border makes this go away, it's a little less pretty but no phantom border appears when this option is on and the window is maximized.

**Comment by MarshallOfSound** [comment]
Closing as upstream (that's how we roll)
