### ISSUE TITLE
Design / UI request

### ISSUE THREAD

**Issue by esni** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#98]
Hello,
This program is amazing, I had been looking for this for months when I found this !
I'm sorry for posting a request in the issue tab, But I believe there is one minor flaw in the design to make it perfect.
In fact, the small orange borders (at the bottom and the sides of the screen) are bothering me, I think it would look cleaner without them.
I understand most people will like it, so I am wondering if you could add a setting for disabling them (or changing their color) for the people who don't like them ?
If that's not possible could I delete a sting of code to hide them ?
Thanks in advance,
Esni

**Comment by MarshallOfSound** [comment]
This is not something I am willing to officially support because if I add an option for something small like this, people will want other options for other small things and then the settings window becomes ridiculous....

If you however want to manually disable them I would recommend looking into this line here  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Material%20Skin/Controls/MaterialForm.cs#L533
